<?php
$LANG_ = array(
"_language" => "Chinese Traditional",
"_charset" => "UTF-8",
);

$LANG_COMMON = array(

	"0" => "頁碼：%1 / %2 ",
	"1" => "忘記密碼",
	"2" => "全部會員",
	"3" => "我的好友",
	"4" => "我的最愛列表",
	"5" => "我的相冊",
	"6" => "我的分類廣告",
	"7" => "我的博客",
	"8" => "我的評論",
	"8a" => "我的交友活動",
	"9" => "發送信息",
	"10" => "發送傳情動漫",
	"11" => "查看詳細資料",
	"12" => "添加到我的最愛列表",
	"13" => "添加到好友列表",
	"14" => "添加到屏蔽列表中",
	"15" => "高級搜索",
	"16" => "添加為我的匹配",
	"17" => "特色活動",
	"18" => "推薦會員",
	"19" => "推薦群組",
	"20" => "推薦視頻",
	"21" => "熱點新聞",
	"22" => "最新精彩博文",
	"23" => "最新照片",
	"24" => "最近更新的會員",
	"25" => "從來沒有更新過",
	"26" => "%1秒鐘之前",
	"27" => "%1分鐘之前",
	"28" => "%1天之前",
	"29" => "%1週之前",
	"30" => "%1個月以前",
	"31" => "%1年以前",
	"32" => "%1個小時以前",
	"33" => "信息已發送",
	"34" => "屏蔽此人信息",
	"35" => "如果您想屏蔽某一類人聯繫您，請在上面的列表中註明。",
	"36" => "我的郵件",
	"37" => "我的群組",
	"38" => "播放視頻",
	"39" => "新郵件",
	"40" => "新朋友",
	"41" => "最新評論",
	"42" => "想要认识这个用户？",
);

$LANG_WELCOME = array(

"_join" => "還不是會員？",
"_join1" => "免費加入, 馬上行動！",
"_join2" => "立即註冊！",

"_ct1" => "免費註冊",
"_ct2" => "開始聊天",
"_ct3" => "交新朋友！",

"_cb1" => "您僅需要花一分鐘的時間，就可以立即創建一個免費帳戶！",
"_cb2" => "我們為您提供各種有效方法認識我們的會員！",
"_cb3" => "尋找您的夢中人約會，一切皆有可能！",

"1" => "最新資訊",
"2" => "閱讀全文",
"3" => "邁向成功的三個步驟！",
"4" => "步驟1: 立即註冊",
"5" => "步驟2: 創建個人檔案",
"6" => "步驟3: 找到夢中人",
"7" => "容易操作，馬上註冊並創建您的個人免費檔案。幾分鐘之內，您將有機會遇到您的夢中人！",
"8" => "快速搜索會員",
"9" => "瀏覽其他會員。",


);
$LANG_HEADINGS = array(

		"home"			=> "Home",
		"subscribe"		=> "My Membership",
		"subscribe_matrix"	=> "Comparison Chart",
		"cryptoconvert" => "Covert Crypto Currency",
		"cryptopayment"	=> "Crypto Currency Payment",
		"register"		=> "Register",
		"register_activation"		=> "Activation",
		"login"			=> "Login",
		"blog"			=> "Blogs",
		"blog_search"		=> "All Blogs",
		"blog_view"			=> "View Blog",
		"blog_add"			=> "Add Blog",
		"calendar"		=> "Events",
		"calendar_view" => "Calendar View",
		"calendar_manage"	=> "Manage Events",
		"calendar_search"	=> "Search Events",
		"calendar_add"      => "Add Events",
		"calendar_events"	=> "Calendar Events",
		"classads"		=> "Classifieds",
		"classads_add"		=>	"Add New Classified",
		"classads_search" 	=> "Search Classifieds",
		"classads_view"    => "View Classads",
		"foundme"			=> "FoundMe",
		"order"			=> "Order",
		"order_thankyou"		=> "Thank You",
		"order_requitix"		=> "Thank You",
		"order_cancel"			=> "Cancel",
		"order_error"			=> "Error",
		"profile"			=> "Profile",
		"profile_admin"		=>	"Profile",
		"profile_overview"	=> "Overview",
		"profile_manage"	=> "Manage",
		"profile_viewfile"	=> "View File",
		"profile_blogview" 	=> "Blog View",
		"gallery"			=> "Gallery",
		"gallery_search"	=> "Search",
		"gallery_manage"	=> "View Albums",
		"gallery_edit"		=> "Edit File",
		"gallery_albums"	=> "View My Album",
		"gallery_create"	=> "Create Album",
		"gallery_upload"	=> "Add Album File",
		"gallery_display"	=> "Display Pic",
		"album_name"		=> "jgjgjg",
		"search"			=> "Search",
		"search_advanced"	=> "Advanced Search",
		"search_detail"	=> "My Friends List",
		"search_friends" => "Friends",
		"search_gallery" => "Gallery",
		"search_1"	=> "My Hot List",
		"search_3"	=> "Blocked List",
		"search_5"	=> "My Partner",
		"groups_search" => "Groups Search",
		"search_inc" => "Search Inc ",
		"search_basic" => "Basic",
		"search_view" => "View Search",
		"viewed_search" => "Viewed Search",
		"viewed"		=> "Profile Viewed",
		"birthday"		=> "Today's Birthday",
		"forum"			=> "Forum",
		"matches"		=> "Quizzes",
		"matches_test"		=> "My Quizzes",
		"matches_taken"		=> "Quizzes I've Taken",
		"matches_addquiz"	=> "Matches Addquiz",
		"matches_add" 		=> "Add Matches",
		"matches_results"	=> "Results Matches",

		"account" 		=> "My Profile",
		"account_comments"	=> "Comments",
		"account_edit"		=> "Edit Account",
		"account_design"	=> "Account Design",
		"music" 		=> "Music",
		"music_search"		=> "All Musics",
		"music_view"		=> "My Music",
		"videos" 		=> "Videos",
		"videos_view" => "videos View",
		"videos_search"		=> "All Videos",
		"friends" 		=> "Friends",
		"games" 		=> "Games",
		"games_search" 	=> "All Games",
		"games_play" 	=> "Play",
		"games_top" => "Leader Board",
		"settings" 		=> "Settings",

		"settings_privacy" => "Privacy Settings",
		"settings_password" => "Chagne Password",
		"settings_cancel" 	=> "Cancel Account",
		"settings_alerts" 	=> "Email Alerts",
		"settings_settings" 	=> "Match Settings",
		"settings_gdpr" 	=> "GDPR",
		"groups"		=> "Groups",
		"groups_view"	=> "View Groups",
		"groups_add"	=> "Add Groups",
		"groups_show"	=> "Show Groups",
		"blogs"			=> "Blogs",
		"classifieds"	=> "Classifieds",
		"events"		=> "Events",
		"recommend"		=> "Recommend",
		"photos"		=> "Photos",
		"contact"		=> "Contact ua",
		"privacy"		=> "Privacy Policy",
		"articles"		=> "Articles",
		"articles_view"		=> "View Article",
		"affiliate"		=> "Affiliates",
		"affiliate_login"	=> "Affiliate Login",
		"affiliate_join"	=> "Affiliate Register",
		"faq"			=> 'FAQs',
		"links"			=>	"Links Page",
		"invite"		=> "Tell a Friend",
		"map"			=> "Site Map",
		"wld"			=> "White Label Dating",
		"wld_login"			=> "Wld Login",
		"wld_register"		=> "Wld Register",
		"wld_dashboard"		=> "Dashboard",
		"wld_create_site"	=> "Create New Site",
		"wld_sites"			=> "My Sites",
		"wld_ads"			=> "Ads",
		"wld_reports"		=> "Reports",
		"wld_wallet"		=> "My Account",
		"wld_help"			=> "Help",
		"messages"			=> "Messages",
		"messages_sent"		=> "Sent",
		"messages_wink"		=> "Wink",
		"messages_inbox"	=> "My Inbox",
		"messages_create"	=> "Send Message",
		"messages_trash"	=> "Trash Can",
		"messages_read" 	=> "Read Message",
		"mgal"				=> "Member Photo Gallery",
		"messages_createcwctest" => "Messages Createcwctest",
		"compatibilityquiz" => "Compatibility Quiz",
		"account_music" => "Profile Music",


);

$LANG_BREADCRUMB = array(

		"home"			=> "Home",
		"subscribe"		=> "My Membership",
		"subscribe_matrix"	=> "Comparison Chart",
		"cryptoconvert" => "Covert Crypto Currency",
		"cryptopayment"	=>	"Crypto Currency Payment",
		"register"		=> "Register",
		"register_activation"		=> "Activation",
		"login"			=> "Login",
		"blog"			=> "Blogs",
		"blog_search"	=> "All Blogs",
		"blog_view"		=> "View Blog",
		"blog_add"		=> "Add Blog",
		"calendar"		=> "Events",
		"calendar_view" => "Calendar View",
		"calendar_add"      => "Add Events",
		"calendar_manage"	=> "Manage Events", 
		"calendar_search"	=> "Search Events",
		"calendar_events"	=> "Calendar Events",
		"classads"		=> "Classifieds",
		"classads_add"		=>	"Add New Classified",
		"classads_search" 	=> "Search Classifieds",
		"classads_view"    => "View Classads",
		"order"			=> "Order",
		"order_thankyou"		=> "Thank You",
		"order_requitix"		=> "Thank You",
		"order_cancel"			=> "Cancel",
		"order_error"			=> "Error",
		"profile"		=> "Profile",
		"profile_admin"		=>	"Profile",
		"profile_overview"	=> "Overview",
		"profile_manage"	=> "Manage",
		"profile_viewfile"	=> "View File",
		"profile_blogview" 	=> "Blog View",
		"gallery"		=> "Gallery",
		"gallery_search"	=> "Search",
		"gallery_manage"	=> "View Albums",
		"gallery_edit"		=> "Edit File",
		"gallery_albums"	=> "View Album",
		"gallery_create"	=> "Create Album",
		"gallery_upload"	=> "Add Album File",
		"gallery_display"	=> "Display Pic",
		"search"		=> "Search",
		"search_advanced"	=> "Advanced Search",
		"search_detail"	=> "My Friends List",
		"search_friends" => "Friends",
		"search_gallery" => "Gallery",
		"search_1"	=> "My Hot List",
		"search_3"	=> "Blocked List",
		"search_5"	=> "My Partner",
		"groups_search" => "Groups Search",
		"search_inc" => "Search Inc ",
		"search_basic" => "Basic",
		"search_view" => "View Search",
		"viewed"		=> "Profile Viewed",
		"viewed_search" => "Viewed Search",
		"birthday"		=> "Today's Birthday", 
		"forum"			=> "Forum",
		"matches"		=> "Quizzes",
		"matches_test"		=> "My Quizzes",
		"matches_taken"		=> "Quizzes I've Taken",
		"matches_addquiz"	=> "Matches Addquiz",
		"matches_add" 		=> "Add Matches",
		"matches_results"	=> "Results Matches",
		"account" 		=> "My Profile",
		"account_comments"	=> "Comments",
		"account_edit"		=> "Edit Account",
		"account_design"	=> "Account Design",
		
		"music" 		=> "Music",
		"music_search"		=> "All Musics",
		"music_view"		=> "My Music",
		"videos" 		=> "Videos",
		"videos_view" => "videos View",
		"videos_search"		=> "All Videos",
		"friends" 		=> "Friends",
		"games" 		=> "Games",
		"games_search" 	=> "All Games",
		"games_play" 	=> "Play",
		"games_top" => "Leader Board",
		"settings" 		=> "Settings",
		"settings_privacy" => "Privacy Settings",
		"settings_gdpr" 	=> "GDPR",
		"settings_password" => "Chagne Password",
		"settings_cancel" 	=> "Cancel Account",
		"settings_alerts" 	=> "Email Alerts",
		"settings_settings" 	=> "Match Settings",
		"groups"		=> "Groups",
		"groups_view"	=> "View Groups",
		"groups_add"	=> "Add Groups",
		"groups_show"	=> "Show Groups",
		"blogs"			=> "Blogs",
		"classifieds"	=> "Classifieds",
		"events"		=> "Events",
		"recommend"		=> "Recommend",
		"contact"		=> "Contact ua",
		"photos"		=> "Photos",
		"privacy"		=> "Privacy Policy",
		"articles"		=> "Articles",
		"articles_view"		=> "View Article",
		"affiliate"		=> "Affiliates",
		"affiliate_login"	=> "Affiliate Login",
		"affiliate_join"	=> "Affiliate Register",
		"faq"			=> 'FAQs',
		"links"			=>	"Links Page",
		"invite"		=> "Tell a Friend",
		"map"			=> "Site Map",
		"wld"			=> "White Label Dating",
		"wld_login"			=> "Wld Login",
		"wld_register"		=> "Wld Register",
		"wld_dashboard"		=> "Dashboard",
		"wld_create_site"	=> "Create New Site",
		"wld_sites"			=> "My Sites",
		"wld_ads"			=> "Ads",
		"wld_reports"		=> "Reports",
		"wld_wallet"		=> "My Account",
		"wld_help"			=> "Help",
		"messages"		=> "Messages",
		"messages_sent"		=> "Sent",
		"messages_wink"		=> "Wink",
		"messages_inbox"	=> "My Inbox",
		"messages_create"	=> "Send Message",
		"messages_trash"	=> "Trash Can",
		"messages_read" 	=> "Read Message",
		"mgal"		=> "Member Photo Gallery",
		"compatibilityquiz" => "Compatibility Quiz",
		"messages_createcwctest" => "Messages Createcwtest",
		"account_music" => "Profile Music",

);

$lang_quick_box = array(
"search" => "Find People",

"articles" => "Articles",

"messages" => "Inbox",

"logout" => "Logout",


);

$LANG_ERROR = array(
"_complete" => "您的帳戶已成功更新",
"_incomplete" => "請如實填寫全部信息",
"_notaccepted" => "您所提供的文件不屬於我們所接受的類型。\n 請從您的電腦上重新選擇正確的文件然後點擊上傳。",
"_error" => "您所輸入的信息有誤。請仔細檢查然後再試一次。",
"_offline1" => "本網站臨時脫機維護",
"_offline2" => "我們的網站信息目前正在更新中，很快將會恢復使用，請稍候！",
"_offline3" => "很抱歉給您帶來不便，謝謝您的耐心等待。",
"_noResults" => "對不起沒有找到結果。",
"_inviteMsg" => "我發現這個超好的網站，我相信您一定會感興趣的，鏈接是",
"_welcomeMsg" => "謝謝！您已成功註冊並可以立即登錄到您的帳戶，
請使用上面及左邊的菜單選項，瀏覽您想要的信息。如果您有任何問題，請聯繫我們，祝您好運、快樂約會！ ",
"_invalid" => "您所輸入的％s地址是無效的",
"_invalidCode" => "您輸入的驗證碼無效，請仔細檢查然後再試一次。",
"_adultWarning" => "如果該文件包含有成人內容，請選擇“是”。",
"_waitingApproval" => "您的帳戶正在等待批准中",

"_AlertQuickMsg" => "請在下面方框中輸入您的信息來聯繫％s ",
 "_AlertQuickWink" => "給％s發送一個傳情動漫。",
"_userBlocked" => "很抱歉，因為您已經被屏蔽，所以無法聯絡該用戶。",

"_videoIntro" => "<p><b>錄製問候視頻！</b></p><p>請插入您的網絡相機及麥克風，然後開始錄製您的問候視頻。 </p><p >如果您準備好了，請點擊“錄製”按鈕，錄制視頻長達5分鐘時，按“停止”按鈕，錄製完成！離開之前，別忘了預覽視頻，然後點擊“保存”。</p >",
"_emailSent" => "謝謝！您的郵件已發送。",

"_noT&C" => "請在方框內打勾，接受本網站的使用條款。",
"_eventWho" => "您希望您的資料只對好友公開還是對所有會員公開？",
"_fileE1" => "該文件已損壞。",
"_fileE2" => "本網站無法識別該照片，請使用其他照片再試一次。",
"_fileE3" => "該文件是空的，請再試一次。",
"_fileE4" => "您的瀏覽器所提交的是錯誤的MIME類型的文件。",
"_fileE5" => "錯誤的文件擴展名。",
"_fileE6" => "很抱歉，我們不支持[%s] 類型的文件, 請上傳一個JPEG格式的圖像文件。",
"_fileE7" => "錯誤的臨時文件。請給該文件重命名，然後上傳一次。",
"_fileE8" => "錯誤的文件，請再試一次，或重新創建文件。",
"_fileE9" => "該文件是空的。",

//
"_noAdultAccess" => "對不起，您沒有權限查看成人資料。",

"_t10" => "熱門會員",
"_t11" => "最受歡迎的會員",

"_t12" => "保存搜索記錄",
"_t13" => "已經保存的搜索記錄",
);
$LANG_UPGRADE = array(
"0" => "謝謝！",
"_complete" => "升級完畢，謝謝！",
"2" => "現在登出",
"_cancel" => "取消訂單",
"4" => "取消升級",
"6" => "升級錯誤",
);
$LANG_BODY = array(

"_yold" => "歲",

// A
"_account" => "帳戶",
"_all" => "全部",
"_add" => "添加",
"_addComment" => "發表評論",
"_approve" => "批准",
"_approved" => "已批准",
"_article" => "精彩博文",
"_articles" => "更多精彩博文",
"_adultContent" => "成人內容",
"_accountOverview" => "帳戶概覽",
"_advert" => "廣告",
"_affiliate" => "商務合作",
"_age" => "年齡",
"_advanced" => "高級",
"_album" => "相冊",
"_albums" => "更多相冊",
"_address" => "地址",
"_attending" => "加入",
//B
"_banners" => "廣告標題",
"_blog" => "博客",
"_blockList" => "屏蔽列表",
//C
"_category" => "類別",
"_created" => "已創建",
"_createNew" => "新建",
"_createdBy" => "創建人",
"_change" => "更改",
"_comments" => "評論",
"_country" => "國家",
"_city" => "所在城鎮/城市",
"_cancel" => "取消",
"_current" => "目前",
"_correct" => "正確",
"_credits" => "積分",
//D
"_delete" => "刪除",
"_deleted" => "已刪除",
"_deselectAll" => "全部取消",
"_date" => "日期",
"_displayPhoto" => "顯示照片",
"_day" => "日",
"_description" => "描述",
//E
"_edit" => "編輯",
"_error" => "出現錯誤",
"_email" => "電子郵件",
"_event" => "活動",
"_events" => "更多活動",
"_everyone" => "每個人",
"_expires" => "過期",

//F
"_fax" => "傳真",
"_faq" => "常見問題",
"_friend" => "好友",
"_friends" => "全部好友",
"_friendsList" => "好友列表",
"_featured" => "有特色的",
"_favorites" => "我的最愛",
"_file" => "文件",
"_files" => "全部文件",
"_fileType" => "類型",
"_forgotten" => "忘記",

//G
"_groups" => "群組",
"_gender" => "性別",
//H
"_hightlighted" => "突出顯示",
"_hotList" => "最愛名單",
//I
"_information" => "資訊",
"_itsFree" => "這是免費的",
"_location" => "所在地",
//J
"_joinToday" => "馬上加入",
"_joined" => "已加入",
//k
"_keyword" => "關鍵字",
//L
"_latest" => "最新的",
"_login" => "登入",
"_lastLogin" => "上次登入",
"_logout" => "登出",
"_link" => "鏈接",
//M
"_manage" => "管理",
"_member" => "會員",
"_members" => "更多會員",
"_message" => "信息",
"_messages" => "全部信息",
"_month" => "月",
"_my" => "我的",
"_mile" => "英哩以內",
"_music" => "音樂",
"_membership" => "會員身份",
//N
"_no" => "否",
"_next" => "下一頁",
"_name" => "姓名",
"_namef" => "名字",
"_namel" => "姓氏",
"_nameb" => "公司名稱",
"_now" => "現在",
"_new" => "新的",
//O
"_options" => "選項",
"_of" => "(屬於）…的",
//P
"_photo" => "照片",
"_photos" => "更多照片",
"_play" => "播放",
"_previous" => "上一頁",
"_page" => "頁數",
"_payments" => "付款",
"_privacy" => "隱私",
//0
"_online" => "在線",
"_onlineNow" => "現在在線",
//V
"_view" => "瀏覽",
"_views" => "瀏覽總數",
"_visitors" => "訪客",
"_viewAll" => "查看全部",
"_verification" => "驗證碼",
"_video" => "視頻",
"_videos" => "更多視頻",
"_visibility" => "能見度",
//q
"_question" => "問題",
"_questions" => "更多問題",
"_quiz" => "我的婚戀小測試",
"_quiz1" => "婚戀小測試",
//U
"_username" => "用戶名",
"_updateAccount" => "更新帳戶",
"_updated" => "已更新",
"_update" => "更新",
//r
"_results" => "結果",
"_recurring" => "週期性",
"_remove" => "刪除",
"_rating" => "評分",
"_rememberMe" => "記住我",
"_register" => "註冊",
"_read" => "閱讀",
"_reply" => "回复",
"_removed" => "已刪除",
//S
"_speadWord" => "傳播消息",
"_save" => "保存",
"_sent" => "已發送",
"_settings" => "設置",
"_search" => "搜索",
"_searchQ" => "快速搜索",
"_select" => "選擇",
"_selectAll" => "選擇全部",
"_submit" => "提交",
"_sort" => "排序方式",
"_send" => "發送",
"_slideshow" => "開始播放變幻圖片",
"_sort0" => "基本視圖",
"_sort1" => "播放影集",
"_sort2" => "詳細查看",
"_sort3" => "最近加入",
"_sort4" => "最近更新",
"_sort5" => "最受歡迎",
"_sort6" => "每頁顯示％s人",
"_street" => "所在街道",
"_status" => "狀態",
"_subject" => "主題",
"_song" => "個人網頁音樂",
//P
"_password" => "密碼",
"_province" => "所在州/省份",
"_phone" => "電話",
"_profile" => "個人資料",
"_partners" => "合作夥伴",
//T
"_thankyou" => "謝謝",
"_topic" => "標題",
"_top10" => "前10名",
"_tags" => "標籤",
"_title" => "稱謂",
"_time" => "時間",
"_today" => "今天",
//Y
"_yes" => "是",
"_year" => "年",
//W
"_watch" => "觀看",
"_website" => "網站",
"_wink" => "拋眉眼",
"_within" => "在…以內",
"_withPics" => "有照片",
"_zipcode" => "郵政編碼",
// MONTHS
"_monday" => "週一",
"_tuesday" => "週二",
"_wednesday" => "週三",
"_thursday" => "週四",
"_friday" => "週五",
"_saturday" => "週六",
"_sunday" => "週日",
// DAYS
"_january" => "一月",
"_febuary" => "二月",
"_march" => "三月",
"_april" => "四月",
"_may" => "五月",
"_june" => "六月",
"_july" => "七月",
"_august" => "八月",
"_september" => "九月",
"_october" => "十月",
"_november" => "十一月",
"_december" => "十二月",

// ALERTS
"_alert1" => "我的信息提醒",
"_atTitle" => "附加相冊",
"_atSub" => "您可以在此上傳相冊，相冊中的所有照片將會出現在本站。",
"_atNo" => "不上傳相冊",


// MODERATOR TEXT
"_mod1" => "版主狀態",
"_mod2" => "現場批准",
"_mod3" => "現場編輯",
"_mod4" => "現場刪除",

"_pChat" => "私下聊天",
"_pLink" => "個人信息鏈接",
"_details" => "詳細信息",

"_pSmsg" => "正在尋找",

"_skype1" => "啟用Skype電話",
"_skype2" => "您只須在上面的方框中輸入您的skype用戶名，我們將會在您的帳戶中設置電話按鈕，這樣您就可以與在線的會員現場聊天了。",

"_seconds" => "秒鐘",
"_minutes" => "分鐘",
"_hours" => "小時",
"_months" => "個月",
"_today" => "今天",
"_ago" => "以前",

"_about" => "About",

"_media" => "Media",

"_compare" => "Compare",

"_compatibilityquiz" => "Compatibility Quiz",

"_email" => "Email",
"_days" => "天",

"_msgSent" => "信息已發送",


 "_home1" => "我是一名",
 "_home2" => "正在尋找",

"_star1" => "摩羯座",
"_star2" => "射手座",
"_star3" => "天蠍座",
"_star4" => "天秤座",
"_star5" => "處女座",
"_star6" => "獅子座",
"_star7" => "巨蟹座",
"_star8" => "雙子座",
"_star9" => "金牛座",
"_star10" => "白羊座",
"_star11" => "雙魚座",
"_star12" => "水瓶座",

//

"_CompleteProfile" => "完成您的個人資料",
"_menue1" => "上次查看過的資料",

"_menue2" => "縮小搜尋範圍",
"_menue3" => "會員快速搜索",
"_menue4" => "關鍵字搜索",
"_menue5" => "今天生日",
"_menue6" => "最後加入",
"_menue7" => "選擇日期",
"_menue8" => "個人簡歷標題",
"_menue9" => "個人簡歷描述",
"_menue10" => "上次登錄",
"_menue11" => "未經批准的會員",
"_weeks" => "週",

 "_fpost" => "發帖",

// IM CHAT
"_imchat1" => "新的聊天請求",
"_imchat2" => "聊天話題",
"_imchat3" => "開始聊天",
"_imchat4" => "拒絕",
"_imchat5" => "Chat",
"_friends3" => "Friends",
"_hotlist3" => "Hostlist",
"_block3" => "Block",
"_wink3" => "Wink",
"_email3" => "Email",
"_email4" => "Send Emails",
"_credits2" => "Credits",
"_balance2" => "Balance:",

);

$lang_global_options = array(
"1" => "您希望.....嗎？",
"2" => "打印此頁",
"3" => "通過電子郵件發送此頁",
"4" => "發表評論",
"5" => "聯繫發帖人",
"6" => "添加到我的最愛",
"7" => "導出到PDF文件",
"8" => "離開該群組",
"9" => "加入該群組",
"10" => "加入該活動",
"11" => "刪除加入狀態",
"12" => "我的聊天狀態",
"13" => "目前在線",
"14" => "休息一會兒！",
"15" => "菜單選項",
"16" => "登出",
"17" => "最近瀏覽",
"18" => "傳播消息",
"19" => "加入會員總數",
"20" => "最近已瀏覽",
"21" => "最近瀏覽",
"22" => "複製頁面鏈接",
 "23" => "留言",
"24" => "給視頻留言",
"25" => "在相冊中留言的會員",
"26" => "在博客中留言的會員",
"27" => "留下評論",
"28" => "登錄",
"29" => "更新個人資料",
"30" => "添加新照片",
"31" => "更換顯示照片",
"32" => "正在加入",
"33" => "添加新群組",
"34" => "把他們的狀態改為",
"35" => "瀏覽全部分類",
"36" => "評級",
"37" => "從相冊中選擇照片作為顯示圖片",
"38" => "您還沒有建立任何檔案呢！請點擊這裡開始！",
"39" => "會員可以發帖",
"40" => "按類別瀏覽",
 "41" => "活動日程表",
"42" => "點擊這裡查看您的當前視頻記錄",
"43" => "點擊這裡錄製新視頻",
"44" => "最近更新的會員",
"45" => "最近的論壇主題",
);

$lang_main_menu = array(

"index" => "首頁",
"search" => "搜索",
"forum" => "論壇",
"groups&sub=search" => "群組",
"blog&sub=search" => "博客",
"classads" => "分類廣告",
"calendar" => "交友活動",
"gallery&sub=search" => "照片",
"games&sub=search" => "遊戲",

);
$lang_main_menu_sub = array(

"account" => "我的個人資料",
"messages" => "信息",
"music&sub=search" => "音樂",
"videos&sub=search" => "視頻",
"friends" => "好友",
"matches" => "婚戀小測試",
"settings" => "設置",
"chatroom" => "聊天室",
"follow" => "追求者",
"logout" => "登出",
);
$lang_main_footer = array(

"privacy" => "隱私權政策",
"articles" => "更多精彩博文",
"affiliate" => "商務合作",
"contact" => "聯繫我們",
"faq" => "常見問題",
"links" => "友情鏈接",
"invite" => "轉告好友",
"map" => "網站地圖",

);
////////////////////////////////////////////////// ///////////////////////////
////////////////////////////////////////////////// //////////////////////////

$LANG_ACCOUNT_MENU = array(
 
"" => "帳戶選項",
"_?" => "",
"&dll=account&sub=view" => "查看我的個人資料",
"&dll=account&sub=view_?" => "審查您的個人資料以便其他會員看到。",
"&dll=gallery" => "我的照片和文件",
"&dll=gallery_?" => "點擊這裡查看及管理您的相冊文件。",
"edit" => "編輯個人資料",
"edit_?" => "點擊選項，在此編輯您的個人信息。",
"design" => "信息創建人",
"design_?" => "點擊下面的選項，定制您的個人資料。",
"video" => "視頻問候",
"video_?" => "點擊選項，在此創建您自己的視頻問候。",
"comments" => "我的評論",
"comments_?" => "在此查看及刪除您對網站的評論。",
"view" => "",
"view_?" => "",
);

$LANG_MESSAGES_MENU = array(

"" => "我的信息",
"_?" => "",
"inbox" => "我的收件箱",
"inbox_?" => "在此查看並管理您的收件箱信息。",
"wink" => "我的傳情動漫",
"wink_?" => "收到新的傳情動漫了嗎？在此選擇您需要的傳情動漫。",
"sent" => "發送郵件",
"sent_?" => "點擊查看您發送的郵件。",
"trash" => "垃圾箱",
"trash_?" => "已刪除的郵件仍然保存在放垃圾箱。請在此清空。",
"create" => "發送信息",
"create_?" => "在此給其他會員發新郵件",
 
);

$LANG_GALLERY_MENU = array(

"search" => "查看全部相冊",
"search_?" => "",
"albums" => "查看我的相冊",
"albums_?" => "在此查看及管理您的網站相冊。",
"create" => "創建新相冊",
"create_?" => "創建新相冊並上傳照片、視頻和音樂等文件。",
"upload" => "添加相冊文件",
"upload_?" => "上傳新視頻、音樂或照片到現有的相冊文件夾中。",
"display" => "更改顯示圖片",
"display_?" => "該顯圖片將是會員登錄時所看到的第一張照片。點擊選項選擇您要顯示的照片。",
"manage" => "",
"manage_?" => "點擊您的任何相冊文件，可以查看具體內容",
"edit" => "",
"edit_?" => "點擊下面選項，編輯您的文件內容。",

);

$LANG_MATCH_MENU = array(

"test" => "我的婚戀小測試",
"test_?" => "點擊選項，添加並管理您的婚戀小測試。",

"addquiz" => "添加新的婚戀小測試",
"addquiz_?" => "",

"results" => "測試結果",
"results_?" => "",

"add" => "管理測試問題",
"add_?" => "",

"taken" => "我已經進行的小測試",
"taken_?" => "查看及管理您已經進行過的兼容性測試。",
);

$LANG_EVENTS_MENU = array(
"events" => "查看全部活動",
"events_?" => "點擊這裡查看所有即將開展的活動",
"add" => "添加活動",
"add_?" => "您聽說過有什麼新活動嗎？趕快告訴大家，並查看其他參加的會員。",
"manage" => "我的活動",
"manage_?" => "點擊這裡管理您目前的活動。",
"search" => "搜索活動",
"search_?" => "",
);
$LANG_GROUPS_MENU = array(
"search" => "查看全部群組",
"search_?" => "在此瀏覽本站的全部群組。",
"add" => "創建群組",
"view" => "查看群組",
"view_?" => "點擊下列選項，瀏覽會員群組",
"add_?" => "趕快創建新群組，並與其他會員一起分享您的興趣愛好。",
"manage" => "我的群組",
"manage_?" => "在此管理您的現有群組",
"show" => "",
"show_?" => "",
);

$LANG_CLASSADS_MENU = array(

"search" => "所有分類廣告",
"search_?" => "瀏覽會員所創建的全部分類廣告",
"manage" => "查看我的分類廣告",
"search&fcid=0_?" => "瀏覽您所創建的全部分類廣告",
"add" => "創建廣告",
"add_?" => "在此創建新的分類廣告。",
"view" => "",
"view_?" => "",
);
$LANG_MUSIC_MENU = array(
"search" => "全部音樂",
"search_?" => "查看其他會員上傳的全部音樂",
"view" => "我的音樂",
"view_?" => "查看並管理您所上傳的音樂文件",
"" => "",
"_?" => "",
);

$LANG_VIDEO_MENU = array(
"search" => "瀏覽全部視頻",
"search_?" => "點擊查看其他會員上傳的所有視頻。",
"myvideos" => "我的視頻",
"myvideos_?" => "下面所列的是您上傳到您的個人帳戶上的所有視頻。",

"view" => "",
"view_?" => "",
);

$LANG_INVITE_MENU = array(
"&dll=invite" => "邀請好友",
"&dll=invite_?" => "點擊選項，給好友發送邀請。",
);
$LANG_1GAME_MENU = array(
"search" => "瀏覽全部遊戲",
"search_?" => "查看並可在此玩耍本站提供的的任何遊戲。",
"top" => "排行榜",
"top_?" => "查看總體評分排行榜。",
"play" => "玩遊戲",
"play_?" => "",
);
$LANG_SETTINGS_MENU = array(

"privacy" => "隱私設置",
"privacy_?" => "管理您的帳戶隱私設置",
"password" => "修改密碼",
"password_?" => "請在此更新您的帳戶登錄密碼。",
"cancel" => "取消帳戶",
"cancel_?" => "要說再見了？如果您想取消帳戶，請通知我們",
"sms" => "我的短信提醒",
"sms_?" => "點擊這裡管理及更新您的短信設置",
"alerts" => "郵件提醒",
"alerts_?" => "管理與更新郵件提醒設置",
"settings" => "匹配設置",
"settings_?" => "請在此選擇您的會員匹配設置，本站將會為您縮小篩選範圍，幫助您找到理想的夢中人。",
"gdpr" => "GDPR",

		"gdpr_?" => "To fully comply with GDPR, you may dwonload your personal data here. <a href='/gdpr' >Download Now</a>",

);
$LANG_BLOG_MENU = array(
"search" => "查看所有博客",
"search_?" => "查看最新會員博客",
"view" => "查看我的博客",
"view_?" => "在此查看與管理網站博客文章。",
"add" => "創建新博客",
"add_?" => "創建新博客，並告訴大家您每天的活動",
);
$LANG_LINKS_MENU = array(

"links" => "友情鏈接",
"links_?" => "如果您想在您的網頁上添加鏈接，請馬上聯繫我們。",

);
// search page
$LANG_SEARCH = array(

"search" => "查看全部會員",
"search_?" => "",

"search&friendid=2" => "我的好友列表",
"search&friendid=2_?" => "",

"search&friendid=1" => "我的最愛列表",
"search&friendid=1_?" => "",

"search&friendid=2&friend_type=3" => "我所屏蔽的名單",
"search&friendid=2&friend_type=3_?" => "",

 
);

$LANG_CHAT_MENU = array(

"chatroom" => "聊天室",
"chatroom_?" => "",
"im" => "即時通訊",
"im_?" => "",
"wink" => "發送傳情動漫",
"wink_?" => "",
"profile" => "查看詳細資料",
"profile_?" => "",
"forum" => "瀏覽論壇",
"forum_?" => "",
);

// contact PAGE
$LANG_CONTACT_MENU = array(

"" => "聯繫我們",
"_?" => "如果您對我們的網站或服務存在疑問，請填寫下表聯繫我們。",


);
// sitemap
$LANG_SITEMAP_MENU = array(

"" => "網站地圖",
"_?" => "下面所列的是網站導航地圖",

);
$LANG_UPGRADE_MENU = array(

"" => "我的會員資格",
"_?" => "請點擊下面的選項，升級您的會員資格",

"matrix" => "比較表",
"matrix_?" => "以下所列的是最新的升級包及訪問功能",
);

$LANG_AFFILIATE_MENU = array(
 
"" => "加盟網絡",
"_?" => "",
"login" => "加盟會員登錄",
"login_?" => "",
"join" => "馬上加入我們的加盟網絡！",
"join_?" => "",
"summary" => "帳戶匯總",
"summary_?" => "",
"banners" => "加盟廣告",
"banners_?" => "",
"edit" => "我的帳戶",
"edit_?" => "",
"payment" => "付款記錄",
"payment_?" => "",
);

$LANG_FORUM_MENU = array(
"" => "社區論壇",
"_?" => "進入以下社區論壇與其他會員聊天",
);
// articles
$LANG_ARTICLES_MENU = array(
"" => "精彩博文",
"_?" => "以下所列的是本站最新的精彩博文",

"view" => "",
"view_?" => "",
);

// subscribe
$lang_subscribe = array(

"" => "升級我的會員資格",
"_?" => "點擊以下選項升級您的會員資格",



"a1" => "升級我的帳戶",
"a3" => "立即升級帳戶！",
"a4" => "我想以後再升級",
"a5" => "立即升級的好處！",
"a6" => "點擊升級包，查看更多功能",
"a7" => "升級包",
"a8" => "付款選擇",
"a9" => "付款方式",
"a10" => "為了幫助您降低費用，當您的初次訂閱到期時，您的使用通行證將會按月自動續期繳費。您隨時可以與我們聯繫取消自動續期。",
"a11" => "我們接受",
"a12" => "付款方式",
"a13" => "選擇付款方式",
"a14" => "現在升級",
"15" => "目前會員資格",
"16" => "銀行匯款/電匯",
"17" => "您所需要做的",
"18" => "請要求您的銀行轉帳",
"19" => "我們遵照以下條款協議。一旦我們收到您的付款，您就可以激活並使用您的帳戶。",
"20" => "額外的短信積分",
);

 
$WINK_MESSAGE_ARRAY = array(
"0" => "我只想問候一聲：你好..",
"1" => "當人們創造字母時就應該把U（您）和I（我）放在一起。",
"2" => "您父親可能是外星人吧，因為這個世界上很難再找到第二個像你這樣的人了！",
"3" => "嗨，我只想給您一個滿意的理由讓您拒絕我，好了您現在就可以對我說“不行”。",
"4" => "您父親以前曾經是摩術大師吧？可能他幫您從高空中摘下閃爍美麗的星星然後放入您的眼睛吧，難怪您長得如此的美麗動人！",
"5" => "您看上去就像書中所描寫的童話故事中的完美王子/公主...那就請別介意我再誇您一次，好嗎？",
"6" => "到底是這裡讓我發熱還是您讓我發熱？",
"7" => "如果我說錯了，您就踢我吧，不過我知道您想親我，對吧？",
"8" => "嗨，我並不想逼你，順便提一下，未經雙方同意我們是不會發生性行為的。",
"9" => "您最喜歡什麼顏色？",
"10" => "您有地圖嗎？我被您迷得神魂顛倒了。",

);

$lang_overview_page = array(

"a7" => "錄製視頻問候",
"a21" => "誰在查看我的個人資料",
"51" => "我的會員資格",
"52" => "個人資料管理",
"53" => "我的照片、影片及音樂等資料",
"54" => "點擊查看您的相冊",
"55" => "編輯說明",
"56" => "點擊編輯個人信息",
"57" => "管理我的好友",
"58" => "點擊查看好友資料",
"59" => "管理我的評論",
"60" => "點擊查看評論",
"61" => "添加及更換顯示圖片",
"62" => "點擊上傳及管理照片",
"63" => "我的匹配設置",
"64" => "點擊並編輯匹配設置",
"65" => "我的隱私設置",
"66" => "點擊並編輯隱私設置",
"67" => "錄製視頻",
"68" => "錄製個人信息",
"69" => "創建新信息",
"70" => "點擊發送新郵件",
"71" => "短信設置 ",
"72" => "點擊查看短信設置",
"73" => "我的郵件提醒設置",
"74" => "點擊編輯電子郵件設置",
"75" => "我的列表",
"76" => "點擊查看您群組",
"77" => "我的群組",
"78" => "點擊查看您群組",
"79" => "我的交友活動",
"80" => "點擊查看您的交友活動",
"81" => "我的分類廣告",
"82" => "點擊查看您的分類廣告",
"83" => "我的博客",
"84" => "點擊查看您的博文",
"86" => "以下是一些有用的鏈接，可以幫助您管理您的個人信息。您可以上傳照片、視頻，音樂等。馬上開始創建完美的個人檔案！",
"87" => "以下是一些有用的鏈接，可以幫助您管理您的個人信息。馬上聯繫其他會員進行交友及娛樂等！",
"88" => "以下是一些有用的鏈接，可以幫助您管理您的網站列表、創建新群組、添加新的分類廣告或撰寫博客。",

//
"89" => "以下是一些有用的鏈接，可以幫助您管理自己的帳戶。您可以重新設計您的個人資料的顏色，更新您的匹配設置等。",
"90" => "匹配會員",
"91" => "點擊會員照片，查看會員詳細資料。",

"92" => "歡迎加入",
"93" => "您的尋找目標是什麼？",

"94" => "更換照片",
"95" => "靠近我",

"96" => "跟我碰面",
"97" => "聊",

);
$lang_register_page = array(

"1" => "該用戶名已被使用",
"2" => "該郵箱已被使用",
"3" => "該郵件地址是無效的",
"4" => "密碼太短！",
"5" => "用戶名太短！",
"6" => "用戶名含有無效字符！",
"7" => "密碼太短！",
"8" => "請如實填寫全部信息",
"9" => "驗證符有誤！",
"10" => "您必須上傳個人照片",
"11" => "謝謝！請查看您的電子郵件獲取激活碼",
"a6" => "會員名稱可以由任意的字母、數字、下劃線及連字符組合，長度最多包含15個字符。不准含有空格、聲調及標點符號。",
"a8" => "請輸入常用的郵件地址，以方便我們給您發送密碼及驗證碼提醒。",
"a10" => "您將需要編輯您的個人資料或檢索郵件。密碼長度必須在4到15個字符之間。",
"a11" => "請重輸密碼",
"a12" => "請按照上面所輸密碼重新輸入。",
"a13" => "所需帳戶詳情",
"a14" => "上傳照片",
"a15" => "選擇一張照片",
"a16" => "最大尺寸：1MB，最小尺寸：105 ×105像素，JPG格式。",
"a17" => "建議：為了達到最佳效果，我們建議您選擇一張能夠突出您臉部的照片，您可拍單獨面對攝像機並讓人容易辨認的照片。",
"a18" => "網站更新",
"a19" => "接收網站新聞資訊",
"a20" => "接收更新及提醒信息",
"a22" => "請輸入圖片中的安全字符以避免自動註冊，並注意區分大小寫。",
"a23" => "我已閱讀、理解並同意遵守",
"a24" => "使用條款",
"a25" => " 使用",
"a26" => "註冊完成",
"28" => "創建帳戶",
"29" => "您的帳戶正在創建中，請稍候！",
"30" => "更新您的帳戶",
"31" => "您的帳戶正在創建中，請稍等！",
"32" => "歡迎您訪問我們的網站",
"33" => "恭喜您！您的帳戶％s已成功建立。",
"34" => "我們已經發送激活郵件到您所提供的以下電子郵件地址:",
"35" => "您必須檢索您賬戶中的電子郵件並點擊郵件中的鏈接。",
"36" => "如果您沒有收到激活郵件，請重新輸入或更改您的電子郵件地址：",
"37" => "请输入有效的电子邮件地址",
"38" => "您的新电子邮件地址已更新。确认电子邮件已经发送给您。",
"39" => "我们无法找到您的帐户详情，请稍后重试。",
);
$lang_account_page = array(
"5" => "短信類型",
"6" => "背景顏色",
"7" => "菜單欄與標題",
"8" => "方框顏色",
"9" => "正文字體",
"10" => "大標題",
"11" => "頁面背景",
"12" => "選擇圖片",
"13" => "文件",
"14" => "顯示類型",
"15" => "刪除已保存的圖像",
"16" => "圖像背景",
"17" => "標題欄背景",
"18" => "標題文字",
"19" => "主要的文字顏色",
"20" => "文本框標題",
"21" => "框頂背景",
"22" => "框體背景",
"23" => "不要重複圖片",
"24" => "標題圖片",
"25" => "垂直重複",
"26" => "橫向重複",
"27" => "您有還沒有發表評論",
"28" => "刪除我的視頻問候",
"29" => "點擊左邊的選項更新您的個人信息顏色。您可以自定義顏色，並上傳自己的背景和標題圖片。",
);
$lang_messages_page = array(

"1" => "您輸入的用戶名不存在。請檢查，再試一次。",
"2" => "您不能給自己發送信息",
"3" => "主題太短",
"4" => "您的信息限額已滿",
"5" => "您已被屏蔽，無法給該用戶發信息",
"a2" => "查看收件箱",
"a3" => "信息正在發送中，請稍候！",
"a4" => "可能需要幾分鐘，謝謝您的耐心等待。",
"a5" => "請輸入以下會員用戶名",
"a6" => "輸入上面的會員用戶名",
"a17" => "閱讀",
"a21" => "發送到",
"a33" => "查看我的收件箱",
"a34" => "信息發送者",
"a35" => "在",
"a36" => "您沒有郵件",
"a38" => "選擇顯示限額",
);
$lang_gallery_page = array(

"1" => "文件上傳失敗",
"2" => "上傳完成",
"3" => "您的帳戶空間已滿",
"4" => "您上傳的音樂文件無效或損壞，請檢查然後再試一次。",
"5" => "您上傳的視頻文件無效或損壞，請檢查然後再試一次。",
"6" => "照片文件類型無效",
"7" => "文件已成功更新",
"8" => "相冊已成功創建，現在上傳文件",
"9" => "相冊已成功更新",
"10" => "文件上傳錯誤",
"a1" => "我的上傳數量",
"a2" => "上傳相冊文件",
"a4" => "文件正在保存中，請稍候！",
"a5" => "根據文件大小可能需要等待幾分鐘。",
"a7" => "選擇您要將文件存入的相冊。",
"a15" => "最大尺寸：1MB，最小尺寸：105 ×105像素，JPG格式。",
"a16" => "建議：為了達到最佳效果，我們建議您選擇一張能夠突出您臉部的照片，您可拍單獨面對攝像機並可讓人容易辨認的照片。",
"a17" => "顯示相片",
"a20" => "將您的照片設為默認圖像並顯示在您的個人資料和搜索結果中。",
"a22" => "最大尺寸：3MB，格式mp3，midi和mpeg。",
"a23" => "建議：為了達到最佳效果，我們建議您選擇音樂文件小於1MB，上傳速度快並可快速收聽。",
"a24" => "輸入YouTube網址",
"a25" => "僅輸入YouTube的網頁地址而已，而不是嵌入代碼。",
"a26" => "例如：複製網站地址，如http://youtube.com/watch?v=Dc541D7ny9I42234，然後粘貼到上面的方框中以收集YouTube視頻。",
"a28" => "最大尺寸：5MB，格式mpg、mpeg、mov、qt、mxu、電影以及DivX文件。",
"a29" => "建議：為了達到最佳效果，我們建議您選擇您最近錄製的視頻。",
"a32" => "上傳文件",
"a40" => "上傳相冊文件",
"a44" => "顯示照片",
"a46" => "您的相冊中沒有任何文件",
"a53" => "該文件中還沒有評論",
"a62" => "上傳相冊文件",
"a64" => "給您的新相冊創建一個描述性的標題，例如：我的暑假照片",
"a66" => "私人相冊",
"a69" => "成人圖片",
"a70" => "公開相冊",
"a71" => "該相冊的可行性選項允許您選擇哪些人可以查看您的相冊文件而哪些人不可以",
"a74" => "給您的文件創建一個有意義的標題",
"76" => "如果您不想用密碼保護您的相冊，請留空白。",
);
$lang_match_page = array(

"1" => "剛剛創建了新的兼容性測試，請點擊這裡參加測試！",
"2" => "測試添加成功，現在您可以添加一些新問題..",
"3" => "測試說明更新",
"4" => "標題太短",
"5" => "問題添加成功",
"6" => "問題成功更新。",
"7" => "謝謝！您的匹配結果已更新",
"8" => "匹配設置已保存",
"a1" => "我的匹配設置",
"a3" => " 當前匹配總數！",
"a4" => "創建新的匹配設置",
"a5" => "搜索匹配結果",
"a8" => "更新我的匹配設置",
"a10" => "輸入一個描述您想要提問的標題，例如：您對我有多了解?",
"a13" => "管理測試",
"a22" => "您還沒有創建任何兼容性測試",
"a31" => "請如實填寫全部五個領域的信息",
"a33" => "匹配問題",
"a36" => "可能的問題答案",
"a37" => "在答案右邊的方框中打勾，選擇您喜歡的答案",
"a42" => "您還沒有輸入任何問題，請在上面的表格中輸入新的問題。",
"a48" => "您的本次測試沒有匹配結果",
"a57" => "參加測試",
"a60" => "我所參加的兼容性測試",
"a61" => "我的測試結果",
"a66" => "您的本次測試沒有匹配結果",
"a67" => "更新設置",
"10" => "選擇測試圖標",
"11" => "測試時間",

);
$lang_ajax = array(
 
"2" => "請投票表達感謝",
"3" => "今天您不能再發送傳情動漫了！",
"4" => "您的傳情動漫已發送給",
"5" => "您的傳情動漫已發送",
"6" => "請登入使用此功能！",
"7" => "會員更新",
"8" => "相冊已成功刪除",
"9" => "評論已成功批准",
"10" => "評論已成功刪除",
"11" => "評論發送審批中。",
"12" => "更新重要照片",
"13" => "匹配結果已刪除",
"14" => "問題已刪除",
"15" => "匹配測試已刪除",
"16" => "評論已刪除",
"17" => "評論已批准",
"18" => "您的評論已被發送審批。",
"19" => "博客文章已刪除",
"24" => "相冊文件已刪除",
"26" => "用戶名太短！",
"27" => "用戶名包含無效字符",
"28" => "該用戶名已被使用，請使用新的名稱再試一次",
"29" => "無效的郵件地址",
"30" => "密碼太短！",
"31" => "必須包含有數字和字母",
"32" => "向您拋媚眼！",
"33" => "您已收到一個媚眼",
"34" => "該會員已在您的列表中。",
"35" => "請登入",
"37" => "每天的郵件",
"38" => "每天的傳情動漫",
"39" => "發送多達",
"40" => "多達",
"41" => "在搜索結果中突出顯示個人資料",
"42" => "成為主頁的精品會員",
"43" => "額外的短信積分",
"44" => "請<a href='index.php?dll=login'>登入</a>發表評論",
"45" => "該電子郵件地址已被使用",
"46" => "請登入，使用此功能！",
"47" => "活動內容已成功更新。",
"48" => "活動內容已成功刪除",

);

// ORDER COMPLETE PAGE
$LANG_ORDER_MENU = array(
"thankyou" => "升級成功",
"thankyou_?" => "謝謝您的訂單！您的帳戶目前正在更新中，請退出您的帳戶，以使更改生效。",
"cancel" => "取消升級",
"cancel_?" => "目前您的帳戶中已沒有餘額，您的升級要求已被取消。如果您有任何疑問，請隨時聯繫我們。",
"error" => "升級錯誤",
"error_?" => "升級期間出現錯誤，如果您對您的帳戶有任何疑問，請立即聯繫我們。",

);
$LANG_TOUR = array(
"a1" => "網站導航",
"a3" => "還不是會員? 請在此註冊",
"a4" => "
<p><strong>歡迎訪問我們的網站</strong><br>這是一個在線社區網站並兼顧到所有的成年人年齡組。立即免費註冊並像生活中尋找志同道合的朋友一樣開始交朋友、約會等！ </p><p>完全免費註冊，點擊下面的按鈕就可以開始了！ <p><p>在我們的網站上有許多高級功能可以幫助您如何開始使用，例如 ;</p>",
"a6" => "<strong>開始</strong><p>註冊步驟既快速又簡單。您可以根據您的個人愛好在您的個人檔案上添加或多或少的信息。</p>< p>您只想填最少的信息？那也可以，您只要填寫必要的姓名、電子郵件地址、出生日期以及職業就可以了。您隨時都可以返回去添加更多信息。</p>一旦您的電子郵件地址被核實後，一切就由您決定。祝您好運，快樂約會！",
"a7" => "<p><strong>開始搜索</strong><br>立即註冊使用我們功能強大的系統來尋找您的完美匹配。快速、易於使用並且讓您有機會搜索到符合您標準的夢中人才是最重要的。無論是他們的外表、宗教、生活方式或專業背景等，我們的系統都為您提供選擇。</p><p>您可以瀏覽盡可能多的會員資料，也可以查看優質相冊，而不像其他大部分的交友網站那樣只顯示一些縮略圖</p>",
"a8" => "<strong>傳情動漫系統</strong><p>如果要您談談您對夢中人有什麼特別的感覺，而您覺得害羞的話，我們會想辦法幫助您搞定。</ p><p>我們先進的傳情動漫系統將會盡量幫助您讓其他會員注意到您對他們感興趣。不必多說，事實勝於雄辯！</p><p>我們的傳情動漫系統內置於我們的短信提醒系統中，並通過您的手機發送任何對您感興趣的會員的信息提醒！</p>",
"a9" => "<p><strong>短信提醒</strong><br><p>我們先進的短信提醒系統會通過短信隨時通知您可能有對您感興趣的人，以便你們可以互相聯繫！</p><p>我們的內置短信提醒系統意味著您可以通過手機接收新媚眼及信息提醒！</p><p>還等什麼，趕快加入！</p>"
);
 
$_LANG_LOGIN = array(
"login" => "會員登錄",
"login_?" => "",
"1" => "該帳戶被暫停",
"2" => "此帳戶尚未激活，請檢查您的電子郵件，並輸入驗證碼。",
"3" => "您的帳戶仍在等待管理員審批中，如果您的帳戶被激活，您將會收到提醒郵件，謝謝您的耐心等待！",
"4" => "您的登錄信息無效，請檢查然後再試一次。",
"5" => "對不起，您輸入的代碼不正確。",
"6" => "您的帳戶已建立，激活鏈接已經發送至您所提供的郵件地址中。請注意：您登錄之前，必須在收到我們發給您的郵件後通過點擊激活鏈接才能激活您的帳戶。 <br><br><p>
如果您沒有收到激活郵件，請檢查您的垃圾郵件文件夾。如果激活郵件也不在垃圾郵件文件夾中，那麼請<a href='index.php?dll=contact'>聯繫</a> 我們，然後我們將會幫助您手動激活您的帳戶。 </a> ",
"7" => "在我們的數據庫中無法找到您的郵件地址。",
"8" => "您的郵件地址無效。請檢查然後再試一次。",
"9" => "您的郵件地址無效。請檢查然後再試一次。",
"10" => "謝謝！我們已經發送新密碼到您的郵箱中。",
"11" => "您的帳號已激活。",
"a3" => "用戶名或郵件地址",
"a7" => "輸入激活碼",
"a11" => "重新發送激活碼",
"a12" => "請輸入您的郵件地址",
"a13" => "激活帳戶",
"a15" => "激活碼",
"a16" => "重新發送代碼",
);


$LANG_INVITE_PAGE = array(
 "7" => "您的登錄信息不正確，請檢查然後再試一次。",
"a28" => "我們已經找到",
"a29" => "聯繫人",
"a30" => "聯繫人已經加為會員。",
"a31" => "您希望我們把您的邀請發送給其他人嗎？",
"a32" => "是的",
"a33" => "不用了，謝謝！",
);
$LANG_GAMES_PAGE = array(
"1" => "上次玩過",
"2" => "已玩過",
"3" => "次數",
"4" => "高級玩家",
"5" => "最高分",
"6" => "排行榜",
"7" => "第二和第三",
"8" => "現在玩遊戲",
 "9" => "全部遊戲",
);

$LANG_SETTINGS = array(

"5" => "手機號碼應該以0為開頭",
"6" => "手機號碼既無效也不正確。",
"7" => "SMS信息已更新",
"9" => "密碼已更新",
"10" => "您的當前密碼不正確",
"11" => "帳戶標記為刪除",
"12" => "重新起用賬戶",
"a1" => "我的手機短信提醒",
"a2" => "我的手機號碼",
"a3" => "注意：請不要在此輸入您的國家代碼，僅須輸入您的手機號碼。",
"a5" => "請注意：該信息將被發送到您所在國家目前正在使用的移動電話中。",
"a6" => "收到新郵件提醒",
"a9" => "當有人給我發新信息時，請提醒我",
"a10" => "收到媚眼提醒",
"a11" => "當有人給我拋媚眼時，請提醒我",
"a12" => "您有",
"a13" => "剩餘短信積分！",
"a14" => "點擊這裡購買更多積分",
"a16" => "我的郵件提醒",
"a17" => "我的郵件地址",
"a18" => "注意：請確保這是一個有效的郵件地址。",
"a19" => "新郵件提醒",
"a20" => "當收到新信息或信息已閱讀時，請提醒我",
"a21" => "新的媚眼提醒",
"a22" => "當有會員向我拋媚眼時，請提醒我",
"a23" => "新的好友請求",
"a24" => "當有會員想把我添加到他們的聯繫人名單時，請通知我。",
"a25" => "新的匹配結果",
"a26" => "我希望收到“社區單身”名單'",
"a27" => "憂惠",
"a28" => "我希望收到加盟憂惠通知",
"a29" => "網絡新聞快訊",
"a30" => "我希望收到社區新聞快訊。",
"a34" => "啟用私下聊天",
"a37" => "我希望在我的個人資料中顯示私聊按鈕",
"a38" => "自動批准新朋友",
"a39" => "如果您希望新的朋友請求自動批准，請選擇“確定”。",
"a40" => "自動批准評論",
"a41" => "當收到新信息或信息已閱讀時，請提醒我",
"a51" => "如果您決定不再需要該帳戶，而且您確定將來不會再使用該用戶名，您可以關閉該帳戶。請在下面的方框中打勾，以確認您想取消該帳戶。您的帳戶在未來7天內將被我們的管理員刪除。",
"a52" => "您確定嗎？",

);


$LANG_AFFILIATE_PAGE = array(
"1" => "帳戶已成功更新",
"2" => "您的帳戶已被暫停",
"3" => "用戶名無效",
"4" => "該郵件地址已被註冊",
"5" => "該郵件地址無效",
"6" => "密碼太短",
"7" => "用戶名地址無效",
"8" => "用戶名包含有無效字符",
"9" => "密碼太短",
"10" => "請如實填寫全部信息",
"11" => "謝謝！您的帳戶已成功創建，您現在就可以登錄。",
"12" => "您的電子郵件地址無效。請檢查，然後再試一次。",
"13" => "您的電子郵件地址無效。請檢查，然後再試一次。",
"14" => "謝謝您！我們已經發送新密碼到您的電子郵箱中。",
"a1" => "加盟項目",
"a2" => "請加入我們的加盟項目",
"a3" => "已經是加盟會員？請在此登錄",
"a4" => "加盟會員登錄信息",
"a14" => "郵政編碼",
"a20" => "支票抬頭請寫",
"a21" => "還不是加盟會員?",
"a23" => "用戶名或電子郵件地址",
"a26" => "請輸入您的電子郵件地址",
"a27" => "交易記錄",
"a29" => "總收入",
"a31" => "已付費",
"a32" => "帳戶已創建",
"a33" => "目前的佣金率",
"a34" => "帳戶匯總",
"a35" => "點擊數",

"a36" => "註冊總數",
"a37" => "總共訂閱",
"a38" => "總收入",
"a39" => "共付費",
"a40" => "餘額",
"a41" => "付款給",
"a42" => "收款人姓名",


);
$GLOBALS['_META'] = $LANG_;
$GLOBALS['LANG_COMMON'] = $LANG_COMMON;
$GLOBALS['_LANG_ERROR'] = $LANG_ERROR;
$GLOBALS['_LANG'] = $LANG_BODY;
$GLOBALS['LANG_NETWORK']= $LANG_INVITE_PAGE;
$GLOBALS['LANG_GAMES'] = $LANG_GAMES_PAGE;
$GLOBALS['LANG_SETTINGS'] = $LANG_SETTINGS;
$GLOBALS['LANG_WELCOME'] = $LANG_WELCOME;
$GLOBALS['LANG_GLO_OPTIONS'] = $lang_global_options;
$GLOBALS['LANG_LOGIN'] = isset($lang_main_sub_sub22);
$GLOBALS['LANG_ORDER'] = $lang_subscribe;
$GLOBALS['LANG_OVERVIEW'] = $lang_overview_page;
$GLOBALS['LANG_REGISTER'] = $lang_register_page;
$GLOBALS['LANG_ACCOUNT'] = $lang_account_page;
$GLOBALS['LANG_MESSAGES'] = $lang_messages_page;
$GLOBALS['LANG_GALLERY'] = $lang_gallery_page;
$GLOBALS['LANG_MATCH'] = $lang_match_page;
$GLOBALS['LANG_AJAX'] = $lang_ajax;
?>