(function(){var a;a="undefined"!==typeof exports?exports:this.Spine={};a.version="0.0.4";var b=a.$=this.jQuery||this.Zepto||function(a){return a},c=a.makeArray=function(a){return Array.prototype.slice.call(a,0)},e=a.isArray=function(a){return"[object Array]"==Object.prototype.toString.call(a)};"undefined"===typeof Array.prototype.indexOf&&(Array.prototype.indexOf=function(a){for(var b=0;b<this.length;b++)if(this[b]===a)return b;return-1});var d=a.Events={bind:function(a,b){var c=a.split(" ");this._callbacks||
(this._callbacks={});for(var e=0;e<c.length;e++)(this._callbacks[c[e]]||(this._callbacks[c[e]]=[])).push(b);return this},trigger:function(){var a=c(arguments),b=a.shift(),e,n;if(!this._callbacks||!(e=this._callbacks[b]))return!1;b=0;for(n=e.length;b<n&&!1!==e[b].apply(this,a);b++);return!0},unbind:function(a,b){if(!a)return this._callbacks={},this;var c,e,d;if(!this._callbacks||!(c=this._callbacks[a]))return this;if(!b)return delete this._callbacks[a],this;e=0;for(d=c.length;e<d;e++)if(b===c[e]){c.splice(e,
1);break}return this}},p=a.Log={trace:!0,logPrefix:"(App)",log:function(){if(this.trace&&"undefined"!=typeof console){var a=c(arguments);this.logPrefix&&a.unshift(this.logPrefix);console.log.apply(console,a);return this}}};"function"!==typeof Object.create&&(Object.create=function(a){function b(){}b.prototype=a;return new b});var x=["included","extended"],g=a.Class={inherited:function(){},created:function(){},prototype:{initialize:function(){},init:function(){}},create:function(a,b){var c=Object.create(this);
c.parent=this;c.prototype=c.fn=Object.create(this.prototype);a&&c.include(a);b&&c.extend(b);c.created();this.inherited(c);return c},init:function(){var a=Object.create(this.prototype);a.parent=this;a.initialize.apply(a,arguments);a.init.apply(a,arguments);return a},proxy:function(a){var b=this;return function(){return a.apply(b,arguments)}},proxyAll:function(){for(var a=c(arguments),b=0;b<a.length;b++)this[a[b]]=this.proxy(this[a[b]])},include:function(a){for(var b in a)-1==x.indexOf(b)&&(this.fn[b]=
a[b]);(a=a.included)&&a.apply(this);return this},extend:function(a){for(var b in a)-1==x.indexOf(b)&&(this[b]=a[b]);(a=a.extended)&&a.apply(this);return this}};g.prototype.proxy=g.proxy;g.prototype.proxyAll=g.proxyAll;g.inst=g.init;g.sub=g.create;a.guid=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;return("x"==a?b:b&3|8).toString(16)}).toUpperCase()};var v=a.Model=g.create();v.extend(d);v.extend({setup:function(a,b){var c=v.sub();a&&(c.name=
a);b&&(c.attributes=b);return c},created:function(a){this.records={};this.attributes=this.attributes?c(this.attributes):[]},find:function(a){a=this.records[a];if(!a)throw"Unknown record";return a.clone()},exists:function(a){try{return this.find(a)}catch(b){return!1}},refresh:function(a){a=this.fromJSON(a);this.records={};for(var b=0,c=a.length;b<c;b++){var e=a[b];e.newRecord=!1;this.records[e.id]=e}this.trigger("refresh");return this},select:function(a){var b=[],c;for(c in this.records)a(this.records[c])&&
b.push(this.records[c]);return this.cloneArray(b)},findByAttribute:function(a,b){for(var c in this.records)if(this.records[c][a]==b)return this.records[c].clone()},findAllByAttribute:function(a,b){return this.select(function(c){return c[a]==b})},each:function(a){for(var b in this.records)a(this.records[b])},all:function(){return this.cloneArray(this.recordsValues())},first:function(){var a=this.recordsValues()[0];return a&&a.clone()},last:function(){var a=this.recordsValues();return(a=a[a.length-
1])&&a.clone()},count:function(){return this.recordsValues().length},deleteAll:function(){for(var a in this.records)delete this.records[a]},destroyAll:function(){for(var a in this.records)this.records[a].destroy()},update:function(a,b){this.find(a).updateAttributes(b)},create:function(a){return this.init(a).save()},destroy:function(a){this.find(a).destroy()},sync:function(a){this.bind("change",a)},fetch:function(a){"function"==typeof a?this.bind("fetch",a):this.trigger("fetch",a)},toJSON:function(){return this.recordsValues()},
fromJSON:function(a){if(a){"string"==typeof a&&(a=JSON.parse(a));if(e(a)){for(var b=[],c=0;c<a.length;c++)b.push(this.init(a[c]));return b}return this.init(a)}},recordsValues:function(){var a=[],b;for(b in this.records)a.push(this.records[b]);return a},cloneArray:function(a){for(var b=[],c=0;c<a.length;c++)b.push(a[c].clone());return b}});v.include({model:!0,newRecord:!0,init:function(a){a&&this.load(a);this.trigger("init",this)},isNew:function(){return this.newRecord},isValid:function(){return!this.validate()},
validate:function(){},load:function(a){for(var b in a)this[b]=a[b]},attributes:function(){for(var a={},b=0;b<this.parent.attributes.length;b++){var c=this.parent.attributes[b];a[c]=this[c]}a.id=this.id;return a},eql:function(a){return a&&a.id===this.id&&a.parent===this.parent},save:function(){var a=this.validate();if(a)return this.trigger("error",this,a),!1;this.trigger("beforeSave",this);this.newRecord?this.create():this.update();this.trigger("save",this);return this},updateAttribute:function(a,
b){this[a]=b;return this.save()},updateAttributes:function(a){this.load(a);return this.save()},destroy:function(){this.trigger("beforeDestroy",this);delete this.parent.records[this.id];this.destroyed=!0;this.trigger("destroy",this);this.trigger("change",this,"destroy")},dup:function(){var a=this.parent.init(this.attributes());a.newRecord=this.newRecord;return a},clone:function(){return Object.create(this)},reload:function(){if(this.newRecord)return this;var a=this.parent.find(this.id);this.load(a.attributes());
return a},toJSON:function(){return this.attributes()},exists:function(){return this.id&&this.id in this.parent.records},update:function(){this.trigger("beforeUpdate",this);var a=this.parent.records;a[this.id].load(this.attributes());a=a[this.id].clone();this.trigger("update",a);this.trigger("change",a,"update")},create:function(){this.trigger("beforeCreate",this);this.id||(this.id=a.guid());this.newRecord=!1;var b=this.parent.records;b[this.id]=this.dup();b=b[this.id].clone();this.trigger("create",
b);this.trigger("change",b,"create")},bind:function(a,b){return this.parent.bind(a,this.proxy(function(a){a&&this.eql(a)&&b.apply(this,arguments)}))},trigger:function(){return this.parent.trigger.apply(this.parent,arguments)}});var w=/^(\w+)\s*(.*)$/,A=a.Controller=g.create({tag:"div",initialize:function(a){this.options=a;for(var c in this.options)this[c]=this.options[c];this.el||(this.el=document.createElement(this.tag));this.el=b(this.el);this.events||(this.events=this.parent.events);this.elements||
(this.elements=this.parent.elements);this.events&&this.delegateEvents();this.elements&&this.refreshElements();this.proxied&&this.proxyAll.apply(this,this.proxied)},$:function(a){return b(a,this.el)},delegateEvents:function(){for(var a in this.events){var b=this.proxy(this[this.events[a]]),c=a.match(w),e=c[1],c=c[2];""===c?this.el.bind(e,b):this.el.delegate(c,e,b)}},refreshElements:function(){for(var a in this.elements)this[this.elements[a]]=this.$(a)},delay:function(a,b){setTimeout(this.proxy(a),
b||0)}});A.include(d);A.include(p);a.App=g.create();a.App.extend(d);A.fn.App=a.App})();(function(){var a=Math,b=/webkit/i.test(navigator.appVersion)?"webkit":/firefox/i.test(navigator.userAgent)?"Moz":"opera"in window?"O":"",c="WebKitCSSMatrix"in window&&"m11"in new WebKitCSSMatrix,e="ontouchstart"in window,d=b+"Transform"in document.documentElement.style,p=/android/gi.test(navigator.appVersion),x=/iphone|ipad/gi.test(navigator.appVersion),g=/playbook/gi.test(navigator.appVersion),v=x||g,w=function(){return window.requestAnimationFrame||window.webkitRequestAnimationFrame||window.mozRequestAnimationFrame||
window.oRequestAnimationFrame||window.msRequestAnimationFrame||function(a){return setTimeout(a,1)}}(),A=window.cancelRequestAnimationFrame||window.webkitCancelRequestAnimationFrame||window.mozCancelRequestAnimationFrame||window.oCancelRequestAnimationFrame||window.msCancelRequestAnimationFrame||clearTimeout,r="onorientationchange"in window?"orientationchange":"resize",q=e?"touchstart":"mousedown",m=e?"touchmove":"mousemove",n=e?"touchend":"mouseup",t=e?"touchcancel":"mouseup",u="Moz"==b?"DOMMouseScroll":
"mousewheel",k="translate"+(c?"3d(":"("),z=c?",0)":")",g=function(a,f){var h=this,s;h.wrapper="object"==typeof a?a:document.getElementById(a);h.wrapper.style.overflow="hidden";h.scroller=h.wrapper.children[0];h.options={hScroll:!0,vScroll:!0,bounce:!0,bounceLock:!1,momentum:!0,lockDirection:!0,useTransform:!0,useTransition:!1,topOffset:0,checkDOMChanges:!1,hScrollbar:!0,vScrollbar:!0,fixedScrollbar:p,hideScrollbar:x,fadeScrollbar:x&&c,scrollbarClass:"",zoom:!1,zoomMin:1,zoomMax:4,doubleTapZoom:2,
wheelAction:"scroll",snap:!1,snapThreshold:1,onRefresh:null,onBeforeScrollStart:function(a){a.preventDefault()},onScrollStart:null,onBeforeScrollMove:null,onScrollMove:null,onBeforeScrollEnd:null,onScrollEnd:null,onTouchEnd:null,onDestroy:null,onZoomStart:null,onZoom:null,onZoomEnd:null};for(s in f)h.options[s]=f[s];h.options.useTransform=d?h.options.useTransform:!1;h.options.hScrollbar=h.options.hScroll&&h.options.hScrollbar;h.options.vScrollbar=h.options.vScroll&&h.options.vScrollbar;h.options.zoom=
h.options.useTransform&&h.options.zoom;h.options.useTransition=v&&h.options.useTransition;h.scroller.style[b+"TransitionProperty"]=h.options.useTransform?"-"+b.toLowerCase()+"-transform":"top left";h.scroller.style[b+"TransitionDuration"]="0";h.scroller.style[b+"TransformOrigin"]="0 0";h.options.useTransition&&(h.scroller.style[b+"TransitionTimingFunction"]="cubic-bezier(0.33,0.66,0.66,1)");h.options.useTransform?h.scroller.style[b+"Transform"]=k+"0,0"+z:h.scroller.style.cssText+=";position:absolute;top:0;left:0";
h.options.useTransition&&(h.options.fixedScrollbar=!0);h.refresh();h._bind(r,window);h._bind(q);e||(h._bind("mouseout",h.wrapper),h._bind(u));h.options.checkDOMChanges&&(h.checkDOMTime=setInterval(function(){h._checkDOMChanges()},500))};g.prototype={enabled:!0,x:0,y:0,steps:[],scale:1,currPageX:0,currPageY:0,pagesX:[],pagesY:[],aniTime:null,wheelZoomCount:0,handleEvent:function(a){switch(a.type){case q:if(!e&&0!==a.button)break;this._start(a);break;case m:this._move(a);break;case n:case t:this._end(a);
break;case r:this._resize();break;case u:this._wheel(a);break;case "mouseout":this._mouseout(a);break;case "webkitTransitionEnd":this._transitionEnd(a)}},_checkDOMChanges:function(){this.moved||this.zoomed||this.animating||this.scrollerW==this.scroller.offsetWidth*this.scale&&this.scrollerH==this.scroller.offsetHeight*this.scale||this.refresh()},_scrollbar:function(l){var f=document,c;this[l+"Scrollbar"]?(this[l+"ScrollbarWrapper"]||(c=f.createElement("div"),this.options.scrollbarClass?c.className=
this.options.scrollbarClass+l.toUpperCase():c.style.cssText="position:absolute;z-index:100;"+("h"==l?"height:7px;bottom:1px;left:2px;right:"+(this.vScrollbar?"7":"2")+"px":"width:7px;bottom:"+(this.hScrollbar?"7":"2")+"px;top:2px;right:1px"),c.style.cssText+=";pointer-events:none;-"+b+"-transition-property:opacity;-"+b+"-transition-duration:"+(this.options.fadeScrollbar?"350ms":"0")+";overflow:hidden;opacity:"+(this.options.hideScrollbar?"0":"1"),this.wrapper.appendChild(c),this[l+"ScrollbarWrapper"]=
c,c=f.createElement("div"),this.options.scrollbarClass||(c.style.cssText="position:absolute;z-index:100;background:rgba(0,0,0,0.5);border:1px solid rgba(255,255,255,0.9);-"+b+"-background-clip:padding-box;-"+b+"-box-sizing:border-box;"+("h"==l?"height:100%":"width:100%")+";-"+b+"-border-radius:3px;border-radius:3px"),c.style.cssText+=";pointer-events:none;-"+b+"-transition-property:-"+b+"-transform;-"+b+"-transition-timing-function:cubic-bezier(0.33,0.66,0.66,1);-"+b+"-transition-duration:0;-"+b+
"-transform:"+k+"0,0"+z,this.options.useTransition&&(c.style.cssText+=";-"+b+"-transition-timing-function:cubic-bezier(0.33,0.66,0.66,1)"),this[l+"ScrollbarWrapper"].appendChild(c),this[l+"ScrollbarIndicator"]=c),"h"==l?(this.hScrollbarSize=this.hScrollbarWrapper.clientWidth,this.hScrollbarIndicatorSize=a.max(a.round(this.hScrollbarSize*this.hScrollbarSize/this.scrollerW),8),this.hScrollbarIndicator.style.width=this.hScrollbarIndicatorSize+"px",this.hScrollbarMaxScroll=this.hScrollbarSize-this.hScrollbarIndicatorSize,
this.hScrollbarProp=this.hScrollbarMaxScroll/this.maxScrollX):(this.vScrollbarSize=this.vScrollbarWrapper.clientHeight,this.vScrollbarIndicatorSize=a.max(a.round(this.vScrollbarSize*this.vScrollbarSize/this.scrollerH),8),this.vScrollbarIndicator.style.height=this.vScrollbarIndicatorSize+"px",this.vScrollbarMaxScroll=this.vScrollbarSize-this.vScrollbarIndicatorSize,this.vScrollbarProp=this.vScrollbarMaxScroll/this.maxScrollY),this._scrollbarPos(l,!0)):this[l+"ScrollbarWrapper"]&&(d&&(this[l+"ScrollbarIndicator"].style[b+
"Transform"]=""),this[l+"ScrollbarWrapper"].parentNode.removeChild(this[l+"ScrollbarWrapper"]),this[l+"ScrollbarWrapper"]=null,this[l+"ScrollbarIndicator"]=null)},_resize:function(){var a=this;setTimeout(function(){a.refresh()},p?200:0)},_pos:function(l,f){l=this.hScroll?l:0;f=this.vScroll?f:0;this.options.useTransform?this.scroller.style[b+"Transform"]=k+l+"px,"+f+"px"+z+" scale("+this.scale+")":(l=a.round(l),f=a.round(f),this.scroller.style.left=l+"px",this.scroller.style.top=f+"px");this.x=l;this.y=
f;this._scrollbarPos("h");this._scrollbarPos("v")},_scrollbarPos:function(l,f){var c="h"==l?this.x:this.y;this[l+"Scrollbar"]&&(c*=this[l+"ScrollbarProp"],0>c?(this.options.fixedScrollbar||(c=this[l+"ScrollbarIndicatorSize"]+a.round(3*c),8>c&&(c=8),this[l+"ScrollbarIndicator"].style["h"==l?"width":"height"]=c+"px"),c=0):c>this[l+"ScrollbarMaxScroll"]&&(this.options.fixedScrollbar?c=this[l+"ScrollbarMaxScroll"]:(c=this[l+"ScrollbarIndicatorSize"]-a.round(3*(c-this[l+"ScrollbarMaxScroll"])),8>c&&(c=
8),this[l+"ScrollbarIndicator"].style["h"==l?"width":"height"]=c+"px",c=this[l+"ScrollbarMaxScroll"]+(this[l+"ScrollbarIndicatorSize"]-c))),this[l+"ScrollbarWrapper"].style[b+"TransitionDelay"]="0",this[l+"ScrollbarWrapper"].style.opacity=f&&this.options.hideScrollbar?"0":"1",this[l+"ScrollbarIndicator"].style[b+"Transform"]=k+("h"==l?c+"px,0":"0,"+c+"px")+z)},_start:function(c){var f=e?c.touches[0]:c,h,s;this.enabled&&(this.options.onBeforeScrollStart&&this.options.onBeforeScrollStart.call(this,
c),(this.options.useTransition||this.options.zoom)&&this._transitionTime(0),this.zoomed=this.animating=this.moved=!1,this.dirY=this.dirX=this.absDistY=this.absDistX=this.distY=this.distX=0,this.options.zoom&&e&&1<c.touches.length&&(s=a.abs(c.touches[0].pageX-c.touches[1].pageX),h=a.abs(c.touches[0].pageY-c.touches[1].pageY),this.touchesDistStart=a.sqrt(s*s+h*h),this.originX=a.abs(c.touches[0].pageX+c.touches[1].pageX-2*this.wrapperOffsetLeft)/2-this.x,this.originY=a.abs(c.touches[0].pageY+c.touches[1].pageY-
2*this.wrapperOffsetTop)/2-this.y,this.options.onZoomStart&&this.options.onZoomStart.call(this,c)),this.options.momentum&&(this.options.useTransform?(h=getComputedStyle(this.scroller,null)[b+"Transform"].replace(/[^0-9-.,]/g,"").split(","),s=1*h[4],h=1*h[5]):(s=1*getComputedStyle(this.scroller,null).left.replace(/[^0-9-]/g,""),h=1*getComputedStyle(this.scroller,null).top.replace(/[^0-9-]/g,"")),s!=this.x||h!=this.y)&&(this.options.useTransition?this._unbind("webkitTransitionEnd"):A(this.aniTime),
this.steps=[],this._pos(s,h)),this.absStartX=this.x,this.absStartY=this.y,this.startX=this.x,this.startY=this.y,this.pointX=f.pageX,this.pointY=f.pageY,this.startTime=c.timeStamp||Date.now(),this.options.onScrollStart&&this.options.onScrollStart.call(this,c),this._bind(m),this._bind(n),this._bind(t))},_move:function(c){var f=e?c.touches[0]:c,h=f.pageX-this.pointX,s=f.pageY-this.pointY,y=this.x+h,r=this.y+s,d=c.timeStamp||Date.now();this.options.onBeforeScrollMove&&this.options.onBeforeScrollMove.call(this,
c);if(this.options.zoom&&e&&1<c.touches.length)y=a.abs(c.touches[0].pageX-c.touches[1].pageX),r=a.abs(c.touches[0].pageY-c.touches[1].pageY),this.touchesDist=a.sqrt(y*y+r*r),this.zoomed=!0,f=1/this.touchesDistStart*this.touchesDist*this.scale,f<this.options.zoomMin?f=.5*this.options.zoomMin*Math.pow(2,f/this.options.zoomMin):f>this.options.zoomMax&&(f=2*this.options.zoomMax*Math.pow(.5,this.options.zoomMax/f)),this.lastScale=f/this.scale,y=this.originX-this.originX*this.lastScale+this.x,r=this.originY-
this.originY*this.lastScale+this.y,this.scroller.style[b+"Transform"]=k+y+"px,"+r+"px"+z+" scale("+f+")",this.options.onZoom&&this.options.onZoom.call(this,c);else{this.pointX=f.pageX;this.pointY=f.pageY;if(0<y||y<this.maxScrollX)y=this.options.bounce?this.x+h/2:0<=y||0<=this.maxScrollX?0:this.maxScrollX;if(r>this.minScrollY||r<this.maxScrollY)r=this.options.bounce?this.y+s/2:r>=this.minScrollY||0<=this.maxScrollY?this.minScrollY:this.maxScrollY;6>this.absDistX&&6>this.absDistY?(this.distX+=h,this.distY+=
s,this.absDistX=a.abs(this.distX),this.absDistY=a.abs(this.distY)):(this.options.lockDirection&&(this.absDistX>this.absDistY+5?(r=this.y,s=0):this.absDistY>this.absDistX+5&&(y=this.x,h=0)),this.moved=!0,this._pos(y,r),this.dirX=0<h?-1:0>h?1:0,this.dirY=0<s?-1:0>s?1:0,300<d-this.startTime&&(this.startTime=d,this.startX=this.x,this.startY=this.y),this.options.onScrollMove&&this.options.onScrollMove.call(this,c))}},_end:function(c){if(!e||0==c.touches.length){var f=this,h=e?c.changedTouches[0]:c,s,r,
d={dist:0,time:0},g={dist:0,time:0},v=(c.timeStamp||Date.now())-f.startTime,q=f.x,w=f.y;f._unbind(m);f._unbind(n);f._unbind(t);f.options.onBeforeScrollEnd&&f.options.onBeforeScrollEnd.call(f,c);if(f.zoomed)q=f.scale*f.lastScale,q=Math.max(f.options.zoomMin,q),q=Math.min(f.options.zoomMax,q),f.lastScale=q/f.scale,f.scale=q,f.x=f.originX-f.originX*f.lastScale+f.x,f.y=f.originY-f.originY*f.lastScale+f.y,f.scroller.style[b+"TransitionDuration"]="200ms",f.scroller.style[b+"Transform"]=k+f.x+"px,"+f.y+
"px"+z+" scale("+f.scale+")",f.zoomed=!1,f.refresh(),f.options.onZoomEnd&&f.options.onZoomEnd.call(f,c);else{if(f.moved){if(300>v&&f.options.momentum){d=q?f._momentum(q-f.startX,v,-f.x,f.scrollerW-f.wrapperW+f.x,f.options.bounce?f.wrapperW:0):d;g=w?f._momentum(w-f.startY,v,-f.y,0>f.maxScrollY?f.scrollerH-f.wrapperH+f.y-f.minScrollY:0,f.options.bounce?f.wrapperH:0):g;q=f.x+d.dist;w=f.y+g.dist;if(0<f.x&&0<q||f.x<f.maxScrollX&&q<f.maxScrollX)d={dist:0,time:0};if(f.y>f.minScrollY&&w>f.minScrollY||f.y<
f.maxScrollY&&w<f.maxScrollY)g={dist:0,time:0}}d.dist||g.dist?(d=a.max(a.max(d.time,g.time),10),f.options.snap&&(g=q-f.absStartX,v=w-f.absStartY,a.abs(g)<f.options.snapThreshold&&a.abs(v)<f.options.snapThreshold?f.scrollTo(f.absStartX,f.absStartY,200):(g=f._snap(q,w),q=g.x,w=g.y,d=a.max(g.time,d))),f.scrollTo(a.round(q),a.round(w),d)):f.options.snap?(g=q-f.absStartX,v=w-f.absStartY,a.abs(g)<f.options.snapThreshold&&a.abs(v)<f.options.snapThreshold?f.scrollTo(f.absStartX,f.absStartY,200):(g=f._snap(f.x,
f.y),(g.x!=f.x||g.y!=f.y)&&f.scrollTo(g.x,g.y,g.time))):f._resetPos(200)}else e&&(f.doubleTapTimer&&f.options.zoom?(clearTimeout(f.doubleTapTimer),f.doubleTapTimer=null,f.options.onZoomStart&&f.options.onZoomStart.call(f,c),f.zoom(f.pointX,f.pointY,1==f.scale?f.options.doubleTapZoom:1),f.options.onZoomEnd&&setTimeout(function(){f.options.onZoomEnd.call(f,c)},200)):f.doubleTapTimer=setTimeout(function(){f.doubleTapTimer=null;for(s=h.target;1!=s.nodeType;)s=s.parentNode;"SELECT"!=s.tagName&&"INPUT"!=
s.tagName&&"TEXTAREA"!=s.tagName&&(r=document.createEvent("MouseEvents"),r.initMouseEvent("click",!0,!0,c.view,1,h.screenX,h.screenY,h.clientX,h.clientY,c.ctrlKey,c.altKey,c.shiftKey,c.metaKey,0,null),r._fake=!0,s.dispatchEvent(r))},f.options.zoom?250:0)),f._resetPos(200);f.options.onTouchEnd&&f.options.onTouchEnd.call(f,c)}}},_resetPos:function(a){var c=0<=this.x?0:this.x<this.maxScrollX?this.maxScrollX:this.x,h=this.y>=this.minScrollY||0<this.maxScrollY?this.minScrollY:this.y<this.maxScrollY?this.maxScrollY:
this.y;c==this.x&&h==this.y?(this.moved&&(this.moved=!1,this.options.onScrollEnd&&this.options.onScrollEnd.call(this)),this.hScrollbar&&this.options.hideScrollbar&&("webkit"==b&&(this.hScrollbarWrapper.style[b+"TransitionDelay"]="300ms"),this.hScrollbarWrapper.style.opacity="0"),this.vScrollbar&&this.options.hideScrollbar&&("webkit"==b&&(this.vScrollbarWrapper.style[b+"TransitionDelay"]="300ms"),this.vScrollbarWrapper.style.opacity="0")):this.scrollTo(c,h,a||0)},_wheel:function(a){var b=this,c,e;
"wheelDeltaX"in a?(c=a.wheelDeltaX/12,e=a.wheelDeltaY/12):c="detail"in a?e=3*-a.detail:e=-a.wheelDelta;"zoom"==b.options.wheelAction?(e=b.scale*Math.pow(2,1/3*(e?e/Math.abs(e):0)),e<b.options.zoomMin&&(e=b.options.zoomMin),e>b.options.zoomMax&&(e=b.options.zoomMax),e!=b.scale&&(!b.wheelZoomCount&&b.options.onZoomStart&&b.options.onZoomStart.call(b,a),b.wheelZoomCount++,b.zoom(a.pageX,a.pageY,e,400),setTimeout(function(){b.wheelZoomCount--;!b.wheelZoomCount&&b.options.onZoomEnd&&b.options.onZoomEnd.call(b,
a)},400))):(c=b.x+c,e=b.y+e,0<c?c=0:c<b.maxScrollX&&(c=b.maxScrollX),e>b.minScrollY?e=b.minScrollY:e<b.maxScrollY&&(e=b.maxScrollY),b.scrollTo(c,e,0))},_mouseout:function(a){var b=a.relatedTarget;if(b)for(;b=b.parentNode;)if(b==this.wrapper)return;this._end(a)},_transitionEnd:function(a){a.target==this.scroller&&(this._unbind("webkitTransitionEnd"),this._startAni())},_startAni:function(){var b=this,c=b.x,e=b.y,r=Date.now(),g,d;b.animating||(b.steps.length?(g=b.steps.shift(),g.x==c&&g.y==e&&(g.time=
0),b.animating=!0,b.moved=!0,b.options.useTransition?(b._transitionTime(g.time),b._pos(g.x,g.y),b.animating=!1,g.time?b._bind("webkitTransitionEnd"):b._resetPos(0)):function B(){var q=Date.now();if(q>=r+g.time)b._pos(g.x,g.y),b.animating=!1,b.options.onAnimationEnd&&b.options.onAnimationEnd.call(b),b._startAni();else if(q=(q-r)/g.time-1,d=a.sqrt(1-q*q),q=(g.x-c)*d+c,b._pos(q,(g.y-e)*d+e),b.animating)b.aniTime=w(B)}()):b._resetPos(400))},_transitionTime:function(a){a+="ms";this.scroller.style[b+"TransitionDuration"]=
a;this.hScrollbar&&(this.hScrollbarIndicator.style[b+"TransitionDuration"]=a);this.vScrollbar&&(this.vScrollbarIndicator.style[b+"TransitionDuration"]=a)},_momentum:function(b,c,e,g,r){c=a.abs(b)/c;var d=c*c/.0012;0<b&&d>e?(e+=r/(6/(d/c*6E-4)),c=c*e/d,d=e):0>b&&d>g&&(g+=r/(6/(d/c*6E-4)),c=c*g/d,d=g);return{dist:d*(0>b?-1:1),time:a.round(c/6E-4)}},_offset:function(a){for(var b=-a.offsetLeft,c=-a.offsetTop;a=a.offsetParent;)b-=a.offsetLeft,c-=a.offsetTop;a!=this.wrapper&&(b*=this.scale,c*=this.scale);
return{left:b,top:c}},_snap:function(b,c){var e,g,d;d=this.pagesX.length-1;e=0;for(g=this.pagesX.length;e<g;e++)if(b>=this.pagesX[e]){d=e;break}d==this.currPageX&&0<d&&0>this.dirX&&d--;b=this.pagesX[d];g=(g=a.abs(b-this.pagesX[this.currPageX]))?a.abs(this.x-b)/g*500:0;this.currPageX=d;d=this.pagesY.length-1;for(e=0;e<d;e++)if(c>=this.pagesY[e]){d=e;break}d==this.currPageY&&0<d&&0>this.dirY&&d--;c=this.pagesY[d];e=(e=a.abs(c-this.pagesY[this.currPageY]))?a.abs(this.y-c)/e*500:0;this.currPageY=d;d=
a.round(a.max(g,e))||200;return{x:b,y:c,time:d}},_bind:function(a,b,c){(b||this.scroller).addEventListener(a,this,!!c)},_unbind:function(a,b,c){(b||this.scroller).removeEventListener(a,this,!!c)},destroy:function(){this.scroller.style[b+"Transform"]="";this.vScrollbar=this.hScrollbar=!1;this._scrollbar("h");this._scrollbar("v");this._unbind(r,window);this._unbind(q);this._unbind(m);this._unbind(n);this._unbind(t);this.options.hasTouch&&(this._unbind("mouseout",this.wrapper),this._unbind(u));this.options.useTransition&&
this._unbind("webkitTransitionEnd");this.options.checkDOMChanges&&clearInterval(this.checkDOMTime);this.options.onDestroy&&this.options.onDestroy.call(this)},refresh:function(){var c,f,e,d=0;f=0;this.scale<this.options.zoomMin&&(this.scale=this.options.zoomMin);this.wrapperW=this.wrapper.clientWidth||1;this.wrapperH=this.wrapper.clientHeight||1;this.minScrollY=-this.options.topOffset||0;this.scrollerW=a.round(this.scroller.offsetWidth*this.scale);this.scrollerH=a.round((this.scroller.offsetHeight+
this.minScrollY)*this.scale);this.maxScrollX=this.wrapperW-this.scrollerW;this.maxScrollY=this.wrapperH-this.scrollerH+this.minScrollY;this.dirY=this.dirX=0;this.options.onRefresh&&this.options.onRefresh.call(this);this.hScroll=this.options.hScroll&&0>this.maxScrollX;this.vScroll=this.options.vScroll&&(!this.options.bounceLock&&!this.hScroll||this.scrollerH>this.wrapperH);this.hScrollbar=this.hScroll&&this.options.hScrollbar;this.vScrollbar=this.vScroll&&this.options.vScrollbar&&this.scrollerH>this.wrapperH;
c=this._offset(this.wrapper);this.wrapperOffsetLeft=-c.left;this.wrapperOffsetTop=-c.top;if("string"==typeof this.options.snap)for(this.pagesX=[],this.pagesY=[],e=this.scroller.querySelectorAll(this.options.snap),c=0,f=e.length;c<f;c++)d=this._offset(e[c]),d.left+=this.wrapperOffsetLeft,d.top+=this.wrapperOffsetTop,this.pagesX[c]=d.left<this.maxScrollX?this.maxScrollX:d.left*this.scale,this.pagesY[c]=d.top<this.maxScrollY?this.maxScrollY:d.top*this.scale;else if(this.options.snap){for(this.pagesX=
[];d>=this.maxScrollX;)this.pagesX[f]=d,d-=this.wrapperW,f++;this.maxScrollX%this.wrapperW&&(this.pagesX[this.pagesX.length]=this.maxScrollX-this.pagesX[this.pagesX.length-1]+this.pagesX[this.pagesX.length-1]);f=d=0;for(this.pagesY=[];d>=this.maxScrollY;)this.pagesY[f]=d,d-=this.wrapperH,f++;this.maxScrollY%this.wrapperH&&(this.pagesY[this.pagesY.length]=this.maxScrollY-this.pagesY[this.pagesY.length-1]+this.pagesY[this.pagesY.length-1])}this._scrollbar("h");this._scrollbar("v");this.zoomed||(this.scroller.style[b+
"TransitionDuration"]="0",this._resetPos(200))},scrollTo:function(a,b,c,e){var d=a;this.stop();d.length||(d=[{x:a,y:b,time:c,relative:e}]);a=0;for(b=d.length;a<b;a++)d[a].relative&&(d[a].x=this.x-d[a].x,d[a].y=this.y-d[a].y),this.steps.push({x:d[a].x,y:d[a].y,time:d[a].time||0});this._startAni()},scrollToElement:function(b,c){var e;if(b=b.nodeType?b:this.scroller.querySelector(b))e=this._offset(b),e.left+=this.wrapperOffsetLeft,e.top+=this.wrapperOffsetTop,e.left=0<e.left?0:e.left<this.maxScrollX?
this.maxScrollX:e.left,e.top=e.top>this.minScrollY?this.minScrollY:e.top<this.maxScrollY?this.maxScrollY:e.top,c=void 0===c?a.max(2*a.abs(e.left),2*a.abs(e.top)):c,this.scrollTo(e.left,e.top,c)},scrollToPage:function(a,b,c){this.options.onScrollStart&&this.options.onScrollStart.call(this);this.options.snap?(a="next"==a?this.currPageX+1:"prev"==a?this.currPageX-1:a,b="next"==b?this.currPageY+1:"prev"==b?this.currPageY-1:b,a=0>a?0:a>this.pagesX.length-1?this.pagesX.length-1:a,b=0>b?0:b>this.pagesY.length-
1?this.pagesY.length-1:b,this.currPageX=a,this.currPageY=b,a=this.pagesX[a],b=this.pagesY[b]):(a*=-this.wrapperW,b*=-this.wrapperH,a<this.maxScrollX&&(a=this.maxScrollX),b<this.maxScrollY&&(b=this.maxScrollY));this.scrollTo(a,b,c||400)},disable:function(){this.stop();this._resetPos(0);this.enabled=!1;this._unbind(m);this._unbind(n);this._unbind(t)},enable:function(){this.enabled=!0},stop:function(){this.options.useTransition?this._unbind("webkitTransitionEnd"):A(this.aniTime);this.steps=[];this.animating=
this.moved=!1},zoom:function(a,c,e,d){var g=e/this.scale;this.options.useTransform&&(this.zoomed=!0,d=void 0===d?200:d,a=a-this.wrapperOffsetLeft-this.x,c=c-this.wrapperOffsetTop-this.y,this.x=a-a*g+this.x,this.y=c-c*g+this.y,this.scale=e,this.refresh(),this.x=0<this.x?0:this.x<this.maxScrollX?this.maxScrollX:this.x,this.y=this.y>this.minScrollY?this.minScrollY:this.y<this.maxScrollY?this.maxScrollY:this.y,this.scroller.style[b+"TransitionDuration"]=d+"ms",this.scroller.style[b+"Transform"]=k+this.x+
"px,"+this.y+"px"+z+" scale("+e+")",this.zoomed=!1)},isReady:function(){return!this.moved&&!this.zoomed&&!this.animating}};"undefined"!==typeof exports?exports.iScroll=g:window.iScroll=g})();/*
 MIT License
*/
(function(){this.Templ=function(a,b){var c=1,e={},d=function(a,b,w,p,r){for(var q=b;-1!=(b=a.indexOf("{%",b));){var m=c++,n=a.indexOf("%}",b),n=a.slice(b+2,n),t="{_"+m+"}";if(r||w&&n.match(w))return w=q-2,n=b+n.length+4,e[m]={buffer:a.slice(w,n),expr:p},a.substr(0,w)+t+a.substr(n);if(m=n.match(/\s*for\s+((?:\w+\s*,)?\s*\w+)\s+in\s+(.+?)\s*$/i))a=d(a,b+2,/\s*endfor\s*/i,{type:"for",elem:m[1],list:m[2]});else if(m=n.match(/\s*if\s+(.+)\s*/i))a=d(a,b+2,/\s*endif\s*/i,{type:"if",cond:m[1]});else if(m=
n.match(/\s*set\s+(\w+)(?:\s*=\s*(.*)?)?\s*/i))n={type:"set",svar:m[1],sval:m[2]},a=m[2]?d(a,b,null,n,!0):d(a,b+2,/\s*endset\s*/i,n);b+=t.length}return a},p=function(a,b){return a=a.replace(/{_(\d+?)}/g,function(a,c){var d=e[c];if(d.expr){var g;switch(d.expr.type){case "if":var m=x(b,d.expr.cond,"TEMPL ERROR: invalid condition: "+d.expr.cond+".");return(g=d.buffer.match(m?/{%\s*if\s+.+?\s*%}([\s\S]*?){%/i:/{%\s*else\s*%}([\s\S]*?){%/i))?p(g[1],b):"";case "for":with(b)var n=eval(d.expr.list);if("undefined"==
typeof n)throw Error('TEMPL ERROR: Undefined list "'+d.expr.list+'".');a:if(g=n,g.hasOwnProperty("length"))g=!!g.length;else{for(var t in g)if(g.hasOwnProperty(t)){g=!0;break a}g=!1}if(g){if(g=d.buffer.match(/{%\s*for.*?\s*%}([\s\S]*?){%/i)){var u,d=d.expr.elem,k=d.split(/\s*,\s*/);t="";2==k.length&&(m=k[0],d=k[1]);for(u in n)k={},m&&(k[m]=u),k[d]=n[u],t+=p(g[1],k);return t}return""}return(g=d.buffer.match(/{%\s*else\s*%}([\s\S]*?){%/i))?p(g[1],n):"";case "set":return m=d.expr,d=m.sval?x(b,m.sval,
""):p(d.buffer.replace(/{%.*?%}/g,""),b),b[m.svar]=d,""}}else{m=x(b,e[c].buffer,'TEMPL ERROR: Undefined variable "'+e[c].buffer+'".');if(d.modif.length)for(n in d.modif){if(void 0==d.modif[n])break;u=d.modif[n];t=[];if(k=d.modif[n].match(/(\w+)\(([\s\S]+)\)/)){u=k[1];t=k[2].split(/\s*,\s*/);with(b)for(g in t)t[g]=eval(t[g])}t.unshift(m);u=Templ.modifiers[u]||window[u];if("function"!=typeof u)throw Error('TEMPL ERROR: Unknown modifier "'+d.modif[n]+'".');m=u.apply(this,t)}return m}})},x=function(a,
c,e){var d;with(a)try{d=eval(c)}catch(r){try{with(b)d=eval(c)}catch(q){try{d=eval(c)}catch(m){throw Error(e);}}}return d};return p(d(function(a){var b=0;for(a=a.replace(/^\s*|\s*$/g,"");-1!=(b=a.indexOf("{{",b));){var d=c++,p=a.indexOf("}}",b),r=a.slice(b+2,p).replace(/^\s*|\s*$/g,"").split("|"),q="{_"+d+"}";e[d]={buffer:r.shift(),modif:r};a=a.substr(0,b)+q+a.substr(p+2);b+=q.length}return a}(a),0),b)};this.Templ.modifiers={};this.Templ.addModifiers=function(a){for(var b in a)this.modifiers[b]=a[b]}})();Templ.addModifiers({upper:function(a){return a.toUpperCase()},lower:function(a){return a.toLowerCase()},capitalize:function(a){return a.charAt(0).toUpperCase()+a.substring(1).toLowerCase()},ucwords:function(a){return a.replace(/^(.)|\s(.)/g,function(a){return a.toUpperCase()})},empty:function(a,b){return a?a:String(b)},trim:function(a,b){var c="undefined"!=typeof b?"[\\s"+b+"]":"\\s";return a.replace(new RegExp("(^"+c+"*)|("+c+"*$)","g"),"")},esc:function(a){return a.replace(/&/g,"&amp;").replace(/</g,
"&lt;").replace(/>/g,"&gt;")},stripTags:function(a){return a.replace(/<\w+(\s+("[^"]*"|'[^']*'|[^>])+)?>|<\/\w+>/gi,"")},truncate:function(a,b,c){b=b||50;c=c||"...";return a.length>b?a.slice(0,b-c.length)+c:String(a)},repeat:function(a,b){return Array((b||1)+1).join(a)},cat:function(){return Array.prototype.slice.call(arguments).join("")},nl2br:function(a){return a.replace(/([^>\r\n]?)(\r\n|\n\r|\r|\n)/g,"$1<br/>")},replace:function(a,b,c){return String(a).replace(new RegExp(b,"gi"),c)},urlEncode:function(a,
b){return b?encodeURIComponent(a):encodeURI(a)}});var _={getParam:function(a){var b=["URL","cookie"],c,e=new RegExp(a+"=(.*?)(?:[;&]|$)");for(c in b)if(a=document[b[c]].match(e))return a[1];return!1},send:function(){this.log("send",arguments);arguments[0]=appSettings.host+arguments[0];$.get.apply(arguments.callee,[].slice.call(arguments))},getRandom:function(){return(""+Math.random()).substr(2)+ +new Date},log:function(){if(window.console){var a=Array.prototype.slice.call(arguments);console.log(a)}},isDeviceScreenWide:function(){return 640<$(window).width()},
findObjInArray:function(a,b,c){for(var e in a)if(a[e][c]==b)return a[e];return!1},dec2hex:function(a){return"#"+(a+16777215+1).toString(16).substr(-6)},regQuote:function(a){return a.replace(RegExp("[.\\\\+*?\\[\\^\\]$(){}=!<>|:\\-]","g"),"\\$&")},cookie:{create:function(a,b,c){c=c||{};var e=c.expires;if("number"==typeof e&&e){var d=new Date;d.setTime(d.getTime()+1E3*e);e=c.expires=d}e&&e.toUTCString&&(c.expires=e.toUTCString());b=encodeURIComponent(b);a=a+"="+b;for(var p in c)a+="; "+p,b=c[p],!0!==
b&&(a+="="+b);document.cookie=a},read:function(a){return(a=document.cookie.match(new RegExp("(?:^|; )"+a.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,"\\$1")+"=([^;]*)")))?decodeURIComponent(a[1]):null},remove:function(a){this.create(a,null,{expires:-1})}}};String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")};
Templ.addModifiers({emotions:function(a){var b=appSettings.emotions||!1;if(!b)return!1;var c=[],e="",d;for(d in b)c.push(d);e=_.regQuote(c.join("~")).replace(/~/g,"|");return a.replace(new RegExp("("+e+")","g"),function(a,c){return b[c]?'<img class="emotion" src="'+appSettings.emotionsPath+"/"+b[c]+'.png">':c})},parseLinks:function(a){for(var b="";""!=a;){var c;var e=a;c=e.indexOf("http://");var d=e.indexOf("https://"),e=e.indexOf("www.");-1==c&&-1==d&&-1==e?c=-1:(-1==c&&(c=999999),-1==d&&(d=999999),
-1==e&&(e=999999),c=Math.min(c,d,e));-1==c?(b+=a,a=""):(b+=a.substr(0,c),a=a.substr(c),c=a.indexOf(" "),-1==c&&(c=a.length),d=a.substr(0,c),b=-1==d.indexOf("http")?b+('<a href="http://'+d+'" target="_blank">'+d+"</a>"):b+('<a href="'+d+'" target="_blank">'+d+"</a>"),a=a.substr(c))}return b}});var JSON;JSON||(JSON={});
(function(){function a(a){return 10>a?"0"+a:a}function b(a){d.lastIndex=0;return d.test(a)?'"'+a.replace(d,function(a){var b=g[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function c(a,e){var d,g,m,n,t=p,u,k=e[a];k&&"object"===typeof k&&"function"===typeof k.toJSON&&(k=k.toJSON(a));"function"===typeof v&&(k=v.call(e,a,k));switch(typeof k){case "string":return b(k);case "number":return isFinite(k)?String(k):"null";case "boolean":case "null":return String(k);case "object":if(!k)return"null";
p+=x;u=[];if("[object Array]"===Object.prototype.toString.apply(k)){n=k.length;for(d=0;d<n;d+=1)u[d]=c(d,k)||"null";m=0===u.length?"[]":p?"[\n"+p+u.join(",\n"+p)+"\n"+t+"]":"["+u.join(",")+"]";p=t;return m}if(v&&"object"===typeof v)for(n=v.length,d=0;d<n;d+=1)"string"===typeof v[d]&&(g=v[d],(m=c(g,k))&&u.push(b(g)+(p?": ":":")+m));else for(g in k)Object.prototype.hasOwnProperty.call(k,g)&&(m=c(g,k))&&u.push(b(g)+(p?": ":":")+m);m=0===u.length?"{}":p?"{\n"+p+u.join(",\n"+p)+"\n"+t+"}":"{"+u.join(",")+
"}";p=t;return m}}"function"!==typeof Date.prototype.toJSON&&(Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()});var e=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
d=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,p,x,g={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},v;"function"!==typeof JSON.stringify&&(JSON.stringify=function(a,b,e){var d;x=p="";if("number"===typeof e)for(d=0;d<e;d+=1)x+=" ";else"string"===typeof e&&(x=e);if((v=b)&&"function"!==typeof b&&("object"!==typeof b||"number"!==typeof b.length))throw Error("JSON.stringify");return c("",{"":a})});
"function"!==typeof JSON.parse&&(JSON.parse=function(a,b){function c(a,e){var d,g,k=a[e];if(k&&"object"===typeof k)for(d in k)Object.prototype.hasOwnProperty.call(k,d)&&(g=c(k,d),void 0!==g?k[d]=g:delete k[d]);return b.call(a,e,k)}var d;a=String(a);e.lastIndex=0;e.test(a)&&(a=a.replace(e,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,
"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return d=eval("("+a+")"),"function"===typeof b?c({"":d},""):d;throw new SyntaxError("JSON.parse");})})();var FC={};FC.BaseController=Spine.Controller.create({el:$("#container"),cont:$("#container"),render:function(a,b){return Templ($(a).html(),b||{})},displayError:function(a){alert(a)}});
FC.ChatApp=FC.BaseController.create({proxied:["onPoll","onLogout"],connected:!1,init:function(a){this.App.settings=a||{};FC.LoadingScreen.init();a=_.getRandom();$.ajaxSetup({data:{sid:a},dataType:"jsonp"});null!=this.connectionTimer&&window.clearInterval(this.connectionTimer);var b=this;b.connectToServer();this.connectionTimer=window.setInterval(function(){b.connected?window.clearInterval(b.connectionTimer):b.connectToServer()},1E4);_.cookie.create("xsid",a);this.App.bind("chatapp:joinroom",this.onJoinRoom);
this.App.bind("chatapp:logout",this.onLogout)},connectToServer:function(){var a=["/connect?appType=mobilechat",this.proxy(this.onPoll)],b=_.cookie.read("xsid");b&&(a.splice(1,0,{xsid:b}),_.cookie.remove("xsid"));_.send.apply(_,a)},onPoll:function(a){try{_.log("onPoll",a);var b=!0;this.connected||(this.connected=!0,this.App.settings.uid?_.send("/autoLogin",{uid:this.App.settings.uid}):FC.LoginScreen.init());if(a)switch(a.action){case "LoginResult":if("error_ban"==a.errorMsg)alert("You are banned.");
else this.onLogin(a);break;case "ReceiveMessage":this.App.trigger("chatscreen:newmessage",a);break;case "OnUserJoin":this.App.trigger("chatscreen:userjoin",a);break;case "OnUserLeave":this.App.trigger("chatscreen:userleave",a);break;case "OnUserLogout":a.param==this.App.user.id&&window.setTimeout('window.location.href = window.location.href.split("?")[0]',1E3);break;case "UserChangeColor":this.App.trigger("chatscreen:userChangeColor",a);break;case "UserChangeAvatar":this.App.trigger("chatscreen:userChangeAvatar",
a);break;case "YouBaned":alert("You are banned.");this.onLogout();window.setTimeout("window.location.reload()",1E3);break;case "OnApplicationSettings":this.App.appsettings=a;_.log("OnApplicationSettings",this.App.appsettings);break;case "LimitationSettings":this.App.limsettings=a,_.log("LimitationSettings",a)}}catch(c){_.log("onPoll error",c)}b=!1;_.send("/poll",this.onPoll);null!=this.connectionErrorCheckTimer&&window.clearTimeout(this.connectionErrorCheckTimer);this.connectionErrorCheckTimer=window.setTimeout(function(){b||
window.setTimeout("window.location.reload()",0)},3E4)},onSendIAmAlive:function(a){},onLogin:function(a){void 0==this.App.appsettings&&_.send("/requestApplicationSettings");var b={error_authentication_failed:"Authentication failed.",error_username_is_already_in_use:"Username is already in use."};if(a.errorMsg)return FC.LoginScreen.init(),this.displayError(b[a.errorMsg]);this.App.user=a.user;null==this.App.user.avatarID&&(this.App.user.avatarID="female"==a.user.gender||"1"==a.user.gender?"02":"01",
_.send("/changeAvatar",{userID:this.App.user.id,avatarID:this.App.user.avatarID}));FC.RoomScreen.init();setInterval(function(){_.send("/sendIAmAlive",this.onSendIAmAlive)},6E4)},onJoinRoom:function(a,b){_.send("/joinRoom",{roomID:a.roomID,password:a.pass},this.proxy(function(a){var e={};a.passIncorrect?e.error="Password is incorrect.":a.result?e.data=a:e.error="Error joining room.";b(e)}))},onLogout:function(a){_.send("/logout",this.proxy(function(){"function"==typeof a&&a()}))}});
FC.LoadingScreen=FC.BaseController.create({init:function(){$("html").addClass("page-not-logged-in");this.cont.html(this.render("#tplLoadingScreen"))}});
FC.LoginScreen=FC.BaseController.create({init:function(){this.cont.html(this.render("#tplLoginScreen"));this.el=$("#login-screen");_.send("/poll",this.guestModeCheck);this.initGuestMode();this.initLogin()},initGuestMode:function(){this.el.find(".login-guest").change(this.proxy(function(){this.el.find("#password-row").toggle();this.el.find("#gender-row").toggle()}))},guestModeCheck:function(a){a&&(this.el=$("#login-screen"),a.guestLogin||this.el.find("#guestCheckBox").remove())},initLogin:function(){this.el.find(".btn-login").click(this.proxy(function(){var a=
this.el.find(".login-username"),b=a.val().trim();if(!b)return this.displayError("Please enter username."),a.focus(),!1;if(this.el.find(".login-guest").is(":checked"))_.send("/guestLogin",{name:b,gender:this.el.find("#gender-row :checked").val()});else{var a=this.el.find(".login-password"),c=a.val().trim();if(!c)return this.displayError("Please enter password."),a.focus(),!1;_.send("/chatLogin",{login:b,pass:c})}}))}});
FC.RoomScreen=FC.BaseController.create({init:function(){$("html").removeClass("page-not-logged-in");_.send("/getRoomList",this.proxy(function(a){for(var b=0;b<a.length;b++){var c=a[b].userLevels;if(-1==c.indexOf(this.App.user.level)&&""!=c||a[b].isPrivate)a.splice(b,1),b--}this.App.rooms=a;this.cont.html(this.render("#tplSelectRoomScreen",{rooms:a}));this.el=$("#room-screen");this.initJoin();this.App.settings.room&&_.send("/joinRoom",{roomID:this.App.settings.room},this.proxy(function(a){this.App.room=
_.findObjInArray(this.App.rooms,a.roomID,"id");(_.isDeviceScreenWide()?FC.ChatScreenWide:FC.ChatScreenNarrow).init()}))}));this.App.bind("chatscreen:userjoin",this.incrOne);this.App.bind("chatscreen:userleave",this.decrOne)},initJoin:function(){this.el.find(".room").click(this.proxy(function(a){var b=$(a.currentTarget).attr("rel");""!=_.findObjInArray(this.App.rooms,b,"id").password?($(a.currentTarget).find(".rpass").show(),$(a.currentTarget).find(".rpassbutton").show()):this.App.trigger("chatapp:joinroom",
{roomID:b,pass:""},this.proxy(function(a){if(a.error)return this.displayError(a.error);this.App.room=_.findObjInArray(this.App.rooms,a.data.roomID,"id");(_.isDeviceScreenWide()?FC.ChatScreenWide:FC.ChatScreenNarrow).init()}))}));this.el.find(".rpassbutton").click(this.proxy(function(a){var b=$(a.currentTarget).parent().find(".rpass");a=b.attr("rel");b=b.attr("value");this.App.trigger("chatapp:joinroom",{roomID:a,pass:b},this.proxy(function(a){if(a.error)return this.displayError(a.error);this.App.room=
_.findObjInArray(this.App.rooms,a.data.roomID,"id");(_.isDeviceScreenWide()?FC.ChatScreenWide:FC.ChatScreenNarrow).init()}))}))},incrOne:function(a){a=$("#"+a.roomID,this.el).find(".user-count span");var b=Number(a.text())+1;a.text(b)},decrOne:function(a){a=$("#"+a.roomID,this.el).find(".user-count span");var b=Number(a.text())-1;a.text(b)}});
FC.ChatScreen=FC.BaseController.create({proxied:["newMessage","userJoin","userLeave","userChangeColor","userChangeAvatar"],components:{},chatSettings:{skin:"default",color:"#0000ff",avatarID:"01",textColor:"#000000",textBold:!1,showTime:!0,showAvatar:!0,imagesPath:"../files/images",emotionsPath:"./img/emotions"},historyLength:0,postInit:function(a){this.initEvents();this.updateUserList(this.App.room.id,this.proxy(function(){this.initRoom();"function"==typeof a&&a()}));$(window).bind("beforeunload",
this.proxy(this.logout));this.adoptHeight();this.App.bind("chatscreen:newmessage",this.newMessage);this.App.bind("chatscreen:userjoin",this.userJoin);this.App.bind("chatscreen:userleave",this.userLeave);this.App.bind("chatscreen:userChangeColor",this.userChangeColor);this.App.bind("chatscreen:userChangeAvatar",this.userChangeAvatar);this.$messageInput=this.el.find("._write-tools ._message-input");this.$messageInput.bind("messagefocus",function(a,c){$(this).val(c).focus()})},initEvents:function(){this.el.find("._write-tools").submit(this.proxy(this.sendMessage));
this.el.delegate(".msg-author","click",this.proxy(this.selectUser))},selectUser:function(a){a=$(a.currentTarget).attr("rel");(a=this.findUser(a).name)&&this.$messageInput.trigger("messagefocus",["to "+a+": "])},getRoomList:function(a){if("undefined"==typeof a)return this.App.rooms;_.send("/getRoomList",this.proxy(function(b){for(var c in b){var e=b[c].userLevels;(-1==e.indexOf(this.App.user.level)&&""!=e||b[c].isPrivate)&&b.splice(c,1)}this.App.rooms=b;a()}))},updateUserList:function(a,b){_.send("/getUserList",
{roomID:a},this.proxy(function(c){this.cacheUserList(c);c.roomID==a&&"undefined"!=typeof b&&b.apply(this,[c])}))},cacheUserList:function(a){this.App.users||(this.App.users={});"undefined"==typeof this.App.users[a.roomID]&&(this.App.users[a.roomID]={});for(var b=this.App.users[a.roomID],c=0,e=a.users.length;c<e;c++)"undefined"==typeof b[a.users[c].id]&&(b[a.users[c].id]=a.users[c])},removeFromUserList:function(a,b){delete this.App.users[a][b]},getUserList:function(a){"undefined"==typeof a&&(a=this.App.room.id);
return this.App.users[a]},adoptHeight:function(){$(".main, .scroller").each(function(){var a=$(this);a.height(function(){var b=0;a.siblings().each(function(){b+=$(this).outerHeight()});return a.parent().innerHeight()-b})})},initRoom:function(){this.createRoom(this.App.room)},createRoom:function(a){this.el.find(".detail-description").remove();this.el.find(".toolbar").find(".half-1:not(._back)").remove().end().append(this.render("#tplTabs",{room:a}));this.el.find("._pages-container").hide();this.el.find("._messages-container").parent().show().end().append(this.render("#tplMessages",
{room:a}));this.selectTab(a);var b=this.el.find("#detail-description");b.hide();a.showDetailDescription&&(b.slideDown("fast","swing"),this.el.find("#tab-"+a.id).click(function(){b.slideToggle("fast","swing")}),this.el.find("#detail-description").click(function(){b.slideToggle("fast","swing")}))},closeRoom:function(a){this.el.find("#tab-"+a).remove();this.el.find("#messages-"+a).remove()},showPasswordField:function(a){a=this.pagesCont.find("li[rel='"+a+"']");a.find(".rpass").show();a.find(".rpassbutton").show()},
selectTab:function(a){this.App.room=a;this.el.find("#tab-"+a.id).addClass("tab-active");this.el.find("#messages-"+a.id).addClass("messages-active");this.getRoomHistory(a.id)},getRoomHistory:function(a){_.send("/getHistory",{roomID:a},this.proxy(function(b){b.roomID==a&&this.appendNewMessages(a,b.history)}))},appendNewMessages:function(a,b){var c=this.el.find("#messages-"+a);if(c){for(var e in b){var d=b[e];d.chatSettings=this.chatSettings;d.message.whisper&&d.message.senderID!=this.App.user.id&&d.message.receiverID!=
this.App.user.id||(0==d.message.content.indexOf("[[DRW]]")?c.append(this.render("#tplDrawing",d)):c.append(this.render("#tplMessage",d)))}this.historyLength+=b.length;this.removeExtraMessages();this.scrollToBottom(c)}else _.log("Error","room with id "+a+" not found")},removeExtraMessages:function(){if(this.historyLength>this.App.settings.maxHistoryMessages){var a=this.el.find("#messages-"+this.App.room.id),b=this.historyLength-this.App.settings.maxHistoryMessages;a.find(".msg:lt("+b+")").remove();
this.historyLength-=b}},scrollToBottom:function(a){this.scrolling.refresh();this.scrolling.vScrollbar&&this.scrolling.scrollToElement(a.find(".msg:last")[0],0)},sendMessage:function(a){a.preventDefault();var b=this.$messageInput.val().trim(),c="";if(!b)return this.$messageInput.focus(),!1;var e=!1;if(a=b.match(/^((.{0,7}).{0,1}to\s+(.*?)\s*:\s*)(.*)/))c=(b=_.findObjInArray(this.App.users[this.App.room.id],a[3],"name"))?b.id:"",b=a[4],e="whisper"==a[2];b={senderID:this.App.user.id,textColor:this.App.user.textColor,
textBold:this.App.user.textBold,content:b,receiverID:c,whisper:e};this.$messageInput.trigger("messagefocus",a?a[1]:"");_.send("/sendMessage",{roomID:this.App.room.id,message:JSON.stringify(b)})},newMessage:function(a){if(this.App.users){var b=this.App.users[a.roomID][a.message.senderID],c=this.App.users[a.roomID][a.message.receiverID];if(!b){b="";_.log("message from unknown user",a.message.senderID);_.log("known users:");for(var e in this.App.users[a.roomID])_.log(this.App.users[a.roomID][e])}c||
(c="");this.appendNewMessages(a.roomID,[{sender:b,receiver:c,message:a.message}])}},userJoin:function(a){this.cacheUserList({roomID:a.roomID,users:[a.user]});this.App.trigger("chatscreen:updateuserlist");this.App.trigger("chatscreen:updateroomlist")},userLeave:function(a){this.removeFromUserList(a.roomID,a.user.id);this.App.trigger("chatscreen:updateuserlist");this.App.trigger("chatscreen:updateroomlist")},userChangeColor:function(a){this.findUser(a.userID).color=a.color},userChangeAvatar:function(a){this.findUser(a.userID).avatarID=
a.avatarID},findUser:function(a){var b=this.App.users,c,e;for(c in b)if(e=b[c][a])return e;return{}},leaveRoom:function(a,b){_.send("/leaveRoom",{roomID:a},function(){"undefined"!=typeof b&&b()})},logout:function(){this.App.trigger("chatapp:logout",this.proxy(function(){this.clearApp();this.clearComponents();FC.ChatApp.init()}))},clearComponents:function(){for(var a in this.components)this.components[a].clear()},clearApp:function(){this.App.room={};this.App.rooms=[];this.App.user={};this.App.users=
[];this.App.unbind()}});FC.ChatScreenWide=FC.ChatScreen.create({init:function(){FC.ChatScreenNarrow.init()}});
FC.ChatScreenNarrow=FC.ChatScreen.create({init:function(){this.cont.html(this.render("#tplChatScreenNarrow",{settings:this.chatSettings}));this.el=$("#container");this.pagesCont=this.el.find("._pages-container");this.postInit(this.proxy(this.initPages));this.App.bind("chatscreen:updateuserlist",this.proxy(function(){this.pagesCont.find("> div").hasClass("tab-content-users")&&this.usersPage()}));this.App.bind("chatscreen:updateroomlist",this.proxy(function(){this.pagesCont.find("> div").hasClass("tab-content-rooms")&&
this.roomsPage()}))},initPages:function(){var a=this,b=this.el.find("._messages-container"),c=this.el.find("._pages-container");this.el.find("._page").click(function(){a.el.find("._room-title").hide();a.el.find(".detail-description").hide();a.el.find("._back").show();$(this).siblings().removeClass("active").end().addClass("active");b.parent().hide();c.show();var e=$(this).attr("rel")+"Page";a[e]()});this.$backToChat=this.el.find("._back-page");this.$backToChat.click(function(e){e.preventDefault();
a.el.find("._page").removeClass("active");a.el.find("._back").hide();a.el.find("._room-title").show();b.parent().show();c.hide()});b.parent().find("#msg-field").attr("maxLength",this.App.appsettings.messageLength);this.initRoomsPage();this.initUsersPage();this.initSettingsPage();this.scrolling=new iScroll("room-msgs-container",{momentum:!1,bounce:!1});$(".tab-content-chat-room").bind("touchmove",function(a){a.preventDefault()})},initRoomsPage:function(){var a=this;this.pagesCont.find(".room").live("click",
function(){var b=$(this).attr("rel"),c=a.App.room?a.App.room.id:"";this.$backToChat=a.el.find("._back-page");b==c?a.$backToChat.trigger("click"):a.leaveRoom(c,a.proxy(function(){this.closeRoom(c);a.App.room=null;this.App.trigger("chatapp:joinroom",{roomID:b,pass:""},this.proxy(function(c){if(c.error)return a.showPasswordField(b),!1;c=_.findObjInArray(this.getRoomList(),b,"id");this.createRoom(c);this.$backToChat.trigger("click")}))}))});this.pagesCont.find(".rpassbutton").live("click",function(b){b.stopPropagation();
b=$(this).parent().find(".rpass");var c=b.attr("rel");b=b.attr("value");a.App.trigger("chatapp:joinroom",{roomID:c,pass:b},a.proxy(function(a){if(a.error)return this.displayError(a.error);a=_.findObjInArray(this.getRoomList(),c,"id");this.createRoom(a);this.$backToChat.trigger("click")}))})},initUsersPage:function(){this.pagesCont.find("._user").live("click",this.proxy(function(a){this.$backToChat.trigger("click");this.selectUser(a)}))},initSettingsPage:function(){var a=this,b=function(){return a.pagesCont.find("._settings-form")};
b().live("submit",function(b){b.preventDefault();$.each($(this).serializeArray(),function(b,c){a.chatSettings[c.name]=c.value});a.applySettings()});this.pagesCont.delegate(".avatar-picker","click",function(){a.pagesCont.find("._settings-select-avatar").toggle()});this.pagesCont.delegate(".text-picker","click",function(){a.pagesCont.find("._settings-select-text").toggle()});var c=function(b,c){var p=a.pagesCont.find(".avatar-picker "+b),x=p.val();p.val(c);return x};this.pagesCont.delegate("._settings-select-avatar .av",
"click",function(){var b=$(this).attr("id").replace("av-",""),d=c("input._avatar",b);$(this).siblings(".active").removeClass("active").end().addClass("active");a.pagesCont.find(".avatar-picker .icon").removeClass("av-"+d).addClass("av-"+b)});this.pagesCont.delegate("._settings-select-avatar .color-item","click",function(){var b="#"+$(this).attr("id").replace("color-","");c("input._color",b);$(this).siblings(".active").removeClass("active").end().addClass("active");a.pagesCont.find(".avatar-picker .icon, ._settings-select-avatar .av").css({backgroundColor:b});
a.pagesCont.find(".avatar-picker .username-sample").css({color:b})});this.pagesCont.delegate("._settings-select-text .color-item","click",function(){var b="#"+$(this).attr("id").replace("color-",""),c=a.pagesCont.find(".text-picker input._color");c.val();c.val(b);$(this).siblings(".active").removeClass("active").end().addClass("active");a.pagesCont.find(".text-picker .usertext-sample").css({color:b})});this.pagesCont.find(".avatar_ok").live("click",function(){b().trigger("submit");a.pagesCont.find(".avatar-picker").trigger("click")});
this.pagesCont.find(".text_ok").live("click",function(){b().trigger("submit");a.pagesCont.find(".text-picker").trigger("click")});this.pagesCont.find("._changable").live("change",function(){b().trigger("submit")})},applySettings:function(){var a=this.cont.find(".main"),b=a.attr("data-skin");a.removeClass(b).addClass(this.chatSettings.skin).attr("data-skin",this.chatSettings.skin);var c=parseInt(this.chatSettings.color.substr(1),16);_.send("/changeColor",{color:c},this.proxy(function(a){this.App.trigger("chatscreen:userChangeColor",
{userID:this.App.user.id,color:c});this.App.user.color=c}));a=parseInt(this.chatSettings.textColor.substr(1),16);this.App.user.textColor=a;this.App.user.textBold="1"==this.chatSettings.textBold;a=this.el.find("._messages-container ._time");+this.chatSettings.showTime?(this.el.removeClass("notime"),a.show()):(this.el.addClass("notime"),a.hide());a=this.el.find("._messages-container ._avatar");+this.chatSettings.showAvatar?(this.el.removeClass("notavatars"),a.show()):(this.el.addClass("notavatars"),
a.hide());if(this.App.user.avatarID!=this.chatSettings.avatarID){var e={userID:this.App.user.id,avatarID:this.chatSettings.avatarID};_.send("/changeAvatar",e,this.proxy(function(){this.App.trigger("chatscreen:userChangeAvatar",e);this.App.user.avatarID=e.avatarID}))}},roomsPage:function(){this.getRoomList(this.proxy(function(){var a=this.render("#tplPagesRooms",{rooms:this.App.rooms,current:this.App.room});this.pagesCont.html(a)}))},usersPage:function(){var a=this.render("#tplPagesUsers",{current:this.App.user,
users:this.getUserList(),room:this.App.room.name});this.pagesCont.html(a)},settingsPage:function(){var a=this.render("#tplPagesSettings",{app:this.App.settings,chatSettings:this.chatSettings,user:this.App.user});this.pagesCont.html(a);this.App.appsettings.allowChangeAvatar||this.pagesCont.find("#settings_avatar").hide();this.App.appsettings.allowChangeMessageColor&&this.App.limsettings.changeMessageColor||this.pagesCont.find("#settings_text_color").hide();this.App.appsettings.allowChangeMessageWeight&&
this.App.limsettings.changeMessageWeight||this.pagesCont.find("#settings_text_weight").hide();(this.App.appsettings.allowChangeMessageColor||this.App.appsettings.allowChangeMessageWeight)&&(this.App.limsettings.changeMessageColor||this.App.limsettings.changeMessageWeight)||this.pagesCont.find("#settings_text").hide()}});
